"""Stage-1 model trainer — MFCC + tiny CNN for the ESP32-S3 sensing node.

Phase-1 deliverable. Trains a micro_speech-class keyword/distress classifier
and exports an int8-quantized .tflite plus a C array for TensorFlow Lite
Micro (drops into firmware/node/ replacing the stage1_score() heuristic).

Dataset layout (16 kHz mono WAV, ~1-4 s clips):

    ml/data/
      scream/       *.wav   (screams — e.g. from the ICTC-2024 scream corpus,
                             human-scream datasets on Kaggle, self-recorded)
      help/         *.wav   ("help", "bachao" utterances — record ~200 per
                             class across speakers; augment below)
      background/   *.wav   (street/traffic/crowd/rain/music negatives —
                             ESC-50 + UrbanSound8K categories work well)

Usage (needs: pip install tensorflow librosa soundfile):

    python ml/train_stage1.py                 # train + export
    python ml/train_stage1.py --epochs 60

Outputs to ml/out/: stage1.keras, stage1_int8.tflite, stage1_model_data.cc
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
OUT_DIR = os.path.join(os.path.dirname(__file__), "out")
CLASSES = ["background", "scream", "help"]        # index 0 must be negative

SR = 16000
CLIP_S = 2.0                # training window
N_MFCC = 13
N_FFT = 512
HOP = 256
FRAMES = int(SR * CLIP_S / HOP) + 1               # ~126


def _die(msg: str) -> None:
    print(f"[train] {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_dataset():
    try:
        import librosa
    except ImportError:
        _die("librosa not installed — pip install tensorflow librosa soundfile")
    X, y = [], []
    for ci, cls in enumerate(CLASSES):
        cdir = os.path.join(DATA_DIR, cls)
        if not os.path.isdir(cdir):
            _die(f"missing dataset dir {cdir} — see the header of this file")
        files = [f for f in os.listdir(cdir) if f.lower().endswith(".wav")]
        print(f"[train] {cls}: {len(files)} clips")
        for f in files:
            audio, _ = librosa.load(os.path.join(cdir, f), sr=SR, mono=True)
            # pad/crop to the window; also make a couple of augmented copies
            variants = [audio]
            variants.append(audio * np.random.uniform(0.5, 1.4))          # gain
            variants.append(np.roll(audio, np.random.randint(0, SR // 2)))  # shift
            for v in variants:
                v = librosa.util.fix_length(v, size=int(SR * CLIP_S))
                mfcc = librosa.feature.mfcc(y=v, sr=SR, n_mfcc=N_MFCC,
                                            n_fft=N_FFT, hop_length=HOP)
                X.append(mfcc.T.astype(np.float32))       # (frames, n_mfcc)
                y.append(ci)
    X = np.stack(X)[..., None]                            # (N, frames, mfcc, 1)
    y = np.array(y, dtype=np.int64)
    print(f"[train] dataset: {X.shape}, classes {np.bincount(y)}")
    return X, y


def build_model():
    import tensorflow as tf
    # Tiny CNN — must stay well under the ESP32-S3's TFLM arena (~200 KB)
    return tf.keras.Sequential([
        tf.keras.layers.Input(shape=(FRAMES, N_MFCC, 1)),
        tf.keras.layers.Conv2D(8, (4, 3), strides=(2, 1), activation="relu"),
        tf.keras.layers.Conv2D(16, (4, 3), strides=(2, 1), activation="relu"),
        tf.keras.layers.Conv2D(24, (4, 3), strides=(2, 2), activation="relu"),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(24, activation="relu"),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(len(CLASSES), activation="softmax"),
    ])


def export_tflite_int8(model, X) -> bytes:
    import tensorflow as tf

    def rep_data():
        for i in np.random.choice(len(X), min(200, len(X)), replace=False):
            yield [X[i:i + 1]]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_data
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def write_c_array(tfl: bytes, path: str) -> None:
    lines = ["// Auto-generated by ml/train_stage1.py — Stage-1 model for TFLM",
             "#include <cstdint>",
             f"alignas(16) const unsigned char g_stage1_model_data[] = {{"]
    for i in range(0, len(tfl), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in tfl[i:i + 12])
        lines.append(f"  {chunk},")
    lines += ["};", f"const int g_stage1_model_data_len = {len(tfl)};", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--batch", type=int, default=32)
    args = ap.parse_args()

    try:
        import tensorflow as tf
    except ImportError:
        _die("tensorflow not installed — pip install tensorflow librosa soundfile")

    X, y = load_dataset()
    idx = np.random.permutation(len(X))
    split = int(0.85 * len(X))
    tr, va = idx[:split], idx[split:]

    model = build_model()
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    model.summary()
    model.fit(X[tr], y[tr], validation_data=(X[va], y[va]),
              epochs=args.epochs, batch_size=args.batch,
              callbacks=[tf.keras.callbacks.EarlyStopping(
                  patience=6, restore_best_weights=True)])

    # Report the numbers the paper needs: per-class recall on the val split
    pred = model.predict(X[va]).argmax(axis=1)
    for ci, cls in enumerate(CLASSES):
        mask = y[va] == ci
        if mask.any():
            rec = float((pred[mask] == ci).mean())
            print(f"[train] {cls:<12} val recall {rec:.3f}  (n={int(mask.sum())})")

    os.makedirs(OUT_DIR, exist_ok=True)
    model.save(os.path.join(OUT_DIR, "stage1.keras"))
    tfl = export_tflite_int8(model, X[tr])
    with open(os.path.join(OUT_DIR, "stage1_int8.tflite"), "wb") as f:
        f.write(tfl)
    write_c_array(tfl, os.path.join(OUT_DIR, "stage1_model_data.cc"))
    print(f"[train] exported int8 tflite ({len(tfl)/1024:.1f} KB) + C array to {OUT_DIR}")
    print("[train] next: wire stage1_model_data.cc into firmware/node/ per "
          "docs/BUILD_AND_OPERATIONS_GUIDE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
