from fastapi.responses import HTMLResponse

def attach(app):
    @app.get('/drone-hardware', response_class=HTMLResponse)
    def drone_hardware_page(): return HTML

HTML=r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VanniKawachh Real F450</title><style>html,body{margin:0;height:100%;overflow:hidden;background:#050a0f;color:#eee;font:12px Segoe UI}#a{display:grid;grid-template-columns:1fr 360px;height:100%}#v{position:relative}canvas{width:100%;height:100%;display:block}#p{overflow:auto;padding:14px;background:#07131c;border-left:1px solid #294653}.b{border:1px solid #294653;border-radius:10px;padding:10px;margin:8px 0;background:#0a1821}.t{font-size:22px;font-weight:900}.s{color:#8fa7b4;font-size:10px;line-height:1.4}.r{display:flex;justify-content:space-between;margin:6px 0}.g{color:#39e6b8}.o{color:#ffb34c}.x{color:#ff6878}button{width:49%;padding:9px;margin:1px 0;background:#122532;color:#fff;border:1px solid #294653;border-radius:7px;font-weight:800}#log{height:80px;overflow:auto;font:10px monospace}</style></head><body><div id="a"><section id="v"><div style="position:absolute;z-index:3;left:12px;top:12px;background:#07131eee;border:1px solid #294653;border-radius:20px;padding:9px 12px"><b>VANNIKAWACHH</b> · REAL F450 HARDWARE</div><canvas id="c"></canvas></section><aside id="p"><div class="t">Actual F450 mesh assembly</div><div class="s">Uses the public Gazebo F450 mesh package instead of procedural placeholder geometry. Base, arms, motor, battery, landing gear and real prop meshes are loaded directly.</div><div class="b"><div id="st" class="t g">IDLE</div><div class="r"><span>Mission</span><b id="mi">—</b></div><div class="r"><span>Speed</span><b id="sp">0.0 m/s</b></div><div class="r"><span>Altitude</span><b id="al">0.0 m</b></div><div class="r"><span>Motor RPM</span><b id="rpm">0</b></div></div><div class="b"><div class="r"><span>Frame</span><b>Flame Wheel F450</b></div><div class="r"><span>Motors</span><b>DJI 2312E 960KV ×4</b></div><div class="r"><span>Props</span><b>F450 prop mesh ×4</b></div><div class="r"><span>FC</span><b>Pixhawk/CubeOrange</b></div><div class="r"><span>GPS</span><b>F9P RTK + compass</b></div></div><div class="b"><div class="r"><span>ESP32 → Hub</span><b id="ln" class="g">STANDBY</b></div><div class="r"><span>Pixhawk → ESC</span><b id="ct" class="g">STANDBY</b></div><div class="r"><span>ESC → motors</span><b id="mt">OFF</b></div><div class="r"><span>Servo → payload</span><b id="sv" class="x">CLOSED</b></div></div><div class="b"><button id="t">TEST DISTRESS</button><button id="e">EXPLODED VIEW</button><button id="as">ASSEMBLED VIEW</button><button id="lh">LIVE HUB</button></div><div id="msg" class="b">Loading F450 meshes…</div><div id="log" class="b"></div></aside></div><script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.185.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.185.0/examples/jsm/"}}</script><script type="module">
import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{STLLoader}from'three/addons/loaders/STLLoader.js';import{ColladaLoader}from'three/addons/loaders/ColladaLoader.js';
const $=x=>document.getElementById(x),R='https://raw.githubusercontent.com/beomsu7/px4-quadrotor-HW-parts/main/custom_f450/meshes/';
const sc=new T.Scene();sc.background=new T.Color(0x050a0f);const cam=new T.PerspectiveCamera(40,1,.01,100);cam.position.set(1.4,1.1,1.8);const ren=new T.WebGLRenderer({canvas:$('c'),antialias:true});ren.setPixelRatio(Math.min(devicePixelRatio,2));const ctl=new OrbitControls(cam,ren.domElement);ctl.enableDamping=true;ctl.minDistance=.5;ctl.maxDistance=6;ctl.target.set(0,.2,0);sc.add(new T.HemisphereLight(0xbfdcff,0x10161c,2));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(3,5,4);sc.add(sun);sc.add(new T.GridHelper(7,14,0x173640,0x0c242d));const d=new T.Group();sc.add(d);const parts=[],props=[];let rpm=0,expl=false;
const M={f:new T.MeshStandardMaterial({color:0x30353a,metalness:.6,roughness:.3}),r:new T.MeshStandardMaterial({color:0xa72c35,metalness:.4,roughness:.3}),w:new T.MeshStandardMaterial({color:0xe4e8ea,roughness:.3}),m:new T.MeshStandardMaterial({color:0x171b20,metalness:.6,roughness:.3}),b:new T.MeshStandardMaterial({color:0x1c625a}),x:new T.MeshStandardMaterial({color:0x245a78})};
function addSTL(file,mat,pos,extra,lab){new STLLoader().load(R+file,g=>{const o=new T.Mesh(g,mat);o.position.set(...pos);o.userData.b=o.position.clone();o.userData.e=new T.Vector3(...extra);o.castShadow=o.receiveShadow=true;d.add(o);parts.push(o);if(lab)console.log(lab)},undefined,e=>log('STL '+file+' failed'))}
function addProp(file,pos,dir){new ColladaLoader().load(R+file,c=>{c.scene.traverse(o=>{if(o.isMesh){o.material=M.w;o.castShadow=o.receiveShadow=true}});c.scene.position.set(...pos);c.scene.scale.setScalar(.35);c.scene.userData.b=c.scene.position.clone();c.scene.userData.e=new T.Vector3(pos[0]*5,1.5,pos[1]*5);c.scene.userData.dir=dir;d.add(c.scene);props.push(c.scene);parts.push(c.scene)},undefined,e=>log('PROP failed'))}
function log(s){$('log').innerHTML+=new Date().toLocaleTimeString()+' '+s+'<br>'}
addSTL('base_link.stl',M.f,[0,0,0],[0,1.1,0],'frame');addSTL('leg_link.stl',M.w,[0,.132,0],[0,-.3,-1.8],'legs');addSTL('battery_link.stl',M.m,[-.025,-.0002,.09],[-1,-.3,0],'battery');
[[.098,.098,0],[.098,-.098,1.57],[-.098,-.098,3.14],[-.098,.098,-1.57]].forEach((p,i)=>addSTL(i%2?'back_arm_link.STL':'front_arm_link.stl',i<2?M.r:M.w,[p[0],p[1],.171],[p[0]*5,1,p[1]*5],'arm'+i));
[[.1599,-.1599],[-.1599,.1599],[.1599,.1599],[-.1599,-.1599]].forEach((p,i)=>{addSTL('motor_link.STL',M.m,[p[0],p[1],.173],[p[0]*5,1.6,p[1]*5],'motor'+i);addProp(i%2?'iris_prop_cw.dae':'iris_prop_ccw_centered.dae',[p[0],p[1],.206],i%2?1:-1)});
const fc=new T.Mesh(new T.BoxGeometry(.16,.045,.11),M.x);fc.position.set(0,.31,.16);d.add(fc);const gps=new T.Mesh(new T.CylinderGeometry(.045,.045,.025,24),M.w);gps.position.set(0,.49,.14);d.add(gps);const servo=new T.Mesh(new T.BoxGeometry(.07,.035,.05),M.r);servo.position.set(.13,-.02,.08);d.add(servo);
function explode(on){expl=on;parts.forEach(o=>{if(o.userData.b)o.position.copy(on?o.userData.e:o.userData.b)});$('e').textContent=on?'ASSEMBLED VIEW':'EXPLODED VIEW'}
function apply(x){const s=x.state||'IDLE';rpm=+x.motor_rpm||0;$('st').textContent=s;$('mi').textContent=x.mission_id||'—';$('sp').textContent=(+x.speed_ms||0).toFixed(1)+' m/s';$('al').textContent=(+x.altitude_m||0).toFixed(1)+' m';$('rpm').textContent=Math.round(rpm);const a=['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].includes(s);$('ln').textContent=s==='IDLE'?'STANDBY':'ACTIVE';$('ct').textContent=a?'COMMANDING':'STANDBY';$('mt').textContent=a?'RUNNING':'OFF';$('sv').textContent=s==='DELIVERING'?'OPEN':'CLOSED'}
function poll(){fetch('/drone_state?x='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(apply).catch(()=>{}).finally(()=>setTimeout(poll,800))}
$('e').onclick=()=>explode(!expl);$('as').onclick=()=>explode(false);$('t').onclick=async()=>{await fetch('/node-alert?node=WEB-F450-REAL&lat=21.128&lon=79.047&event=1&conf=.99&pir=1&light=30');log('DISTRESS SENT')};$('lh').onclick=()=>poll();function resize(){const r=$('v').getBoundingClientRect();cam.aspect=r.width/r.height;cam.updateProjectionMatrix();ren.setSize(r.width,r.height,false)}addEventListener('resize',resize);resize();poll();const clock=new T.Clock();function loop(){requestAnimationFrame(loop);const dt=clock.getDelta(),w=rpm*Math.PI*2/60*dt*.8;props.forEach((p,i)=>p.rotation.z+=w*(p.userData.dir||1));ctl.update();ren.render(sc,cam)}loop();
</script></body></html>'''