"""Labeled CAD-style F450 hardware assembly for VanniKawachh."""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-hardware", response_class=HTMLResponse)
    def drone_hardware_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | F450 Hardware Assembly</title>
<style>
:root{--bg:#050a0f;--panel:#07131c;--line:#2a4653;--txt:#edf7fa;--muted:#91a8b5;--power:#ffb34c;--data:#68b8ff;--ctrl:#35e2b3;--pay:#ff6875}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 450px;height:100vh}#view{position:relative;min-width:0}#c{width:100%;height:100%;display:block}.top{position:absolute;z-index:10;left:13px;right:13px;top:13px;display:flex;justify-content:space-between}.pill{background:#07131ee8;border:1px solid var(--line);border-radius:999px;padding:9px 12px}.pill b{color:#fff}
#labels{position:absolute;inset:0;pointer-events:none}.label{padding:4px 6px;border:1px solid #3a5562;border-radius:5px;background:#061017dd;color:#fff;font-size:10px;white-space:nowrap}.label small{display:block;color:#91a8b5;font-size:8px}
#side{overflow:auto;background:#07121bf8;border-left:1px solid var(--line);padding:13px}.title{font-size:22px;font-weight:900}.sub,.note{font-size:10px;color:var(--muted);line-height:1.55}.card{background:linear-gradient(180deg,#0d1d27,#08131c);border:1px solid var(--line);border-radius:12px;padding:11px;margin:9px 0}.lab{font-size:10px;letter-spacing:.1em;color:var(--muted);font-weight:900}.big{font-size:28px;font-weight:900;margin:2px 0}.ok{color:var(--ctrl)}.warn{color:var(--power)}.bad{color:#ff6875}.row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.val{font-weight:900;text-align:right}.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;color:#667f8c}.step.done{background:#0c211b;color:#b0f5e3;border-color:#286b5a}.step.active{background:#211a10;color:#ffe0a1;border-color:#916729}.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:3px;align-items:center}.node{padding:7px 3px;border:1px solid #294653;border-radius:7px;text-align:center;font-size:8px}.node.active{border-color:var(--ctrl);box-shadow:0 0 12px #35e2b333}.legend{display:grid;grid-template-columns:1fr 1fr;gap:6px;font-size:9px}.legend div{padding:7px;border:1px solid var(--line);border-radius:7px}.sw{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:6px}.btns{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);border-radius:8px;padding:10px;background:#122432;color:#fff;font-weight:900;cursor:pointer}.btn.primary{background:#0d2d25;border-color:#286b5a}.btn.warn{background:#2a2113;border-color:#705025}.btn:disabled{opacity:.45}.status{padding:9px;border:1px solid var(--line);border-radius:8px;background:#061016;font-size:10px}.good{border-color:#286b5a;color:#b0f5e3}.err{border-color:#913443;color:#ffbac1}.log{height:82px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px/1.45 monospace;color:#8fb9c7}
@media(max-width:900px){#app{grid-template-columns:1fr}#side{position:absolute;right:0;top:0;bottom:0;width:min(450px,96vw);z-index:20;box-shadow:-20px 0 50px #000c}}
</style>
</head>
<body>
<div id="app"><section id="view"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · F450 / PIXHAWK HARDWARE LAB</div><div class="pill">SOURCE: <b id="source">CHECKING</b></div></div><canvas id="c"></canvas><div id="labels"></div></section>
<aside id="side"><div class="title">Physical Drone Assembly</div><div class="sub">A component-level engineering view based on an F450/CubeOrange reference configuration. The 3D assembly shows where the flight controller, power module, LiPo, GPS, telemetry computer, ESCs, motors, props and health-kit actuator sit. This is intentionally different from the geographic flight page.</div>
<div class="card"><div class="lab">LIVE MISSION</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Motor RPM</span><span id="rpm" class="val">0</span></div><div class="row"><span>Battery</span><span id="battery" class="val">100%</span></div></div>
<div class="card"><div class="lab">POWER PATH</div><div class="row"><span>4S 4500 mAh LiPo → power module</span><span class="val" style="color:var(--power)">POWER</span></div><div class="row"><span>Power module → ESC ×4</span><span id="esc" class="val">READY</span></div><div class="row"><span>ESC → BLDC motors ×4</span><span id="motors" class="val">OFF</span></div><div class="row"><span>Motors → DJI 9450 props ×4</span><span id="props" class="val">STOPPED</span></div></div>
<div class="card"><div class="lab">CONTROL / DATA</div><div class="row"><span>F9P GPS + compass → CubeOrange</span><span class="val" style="color:var(--data)">DATA</span></div><div class="row"><span>ESP32 → Hub → companion/telemetry</span><span id="link" class="val" style="color:var(--data)">STANDBY</span></div><div class="row"><span>Companion → Pixhawk TELEM</span><span id="fc" class="val" style="color:var(--ctrl)">STANDBY</span></div><div class="row"><span>Pixhawk MAIN OUT → ESC ×4</span><span id="ctrl" class="val" style="color:var(--ctrl)">STANDBY</span></div><div class="row"><span>Servo output → health-kit release</span><span id="servo" class="val" style="color:var(--pay)">CLOSED</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div id="s1" class="step">Distress received</div><div id="s2" class="step">Companion / mission command</div><div id="s3" class="step">Pixhawk arms</div><div id="s4" class="step">ESCs spool</div><div id="s5" class="step">Vertical takeoff</div><div id="s6" class="step">Cruise / hover</div><div id="s7" class="step">Payload servo opens</div><div id="s8" class="step">Health kit released</div><div id="s9" class="step">RTL / landing</div></div></div>
<div class="card"><div class="lab">SIGNAL LEGEND</div><div class="legend"><div><span class="sw" style="background:var(--power)"></span>Power</div><div><span class="sw" style="background:var(--data)"></span>Sensor / telemetry</div><div><span class="sw" style="background:var(--ctrl)"></span>Flight control</div><div><span class="sw" style="background:var(--pay)"></span>Payload</div></div></div>
<div class="card"><div class="lab">CONTROL CHAIN</div><div class="chain"><div id="n1" class="node">ESP32<br>SENSOR</div><div>→</div><div id="n2" class="node">HUB<br>DISPATCH</div><div>→</div><div id="n3" class="node">PIXHAWK<br>ARDUPILOT</div><div>→</div><div id="n4" class="node">ESCs<br>+ SERVO</div></div></div>
<div class="btns"><button id="live" class="btn primary">LIVE HUB</button><button id="test" class="btn">TEST DISTRESS</button><button id="explode" class="btn warn">EXPLODED VIEW</button><button id="assemble" class="btn">ASSEMBLED VIEW</button></div>
<div id="status" class="status">Starting F450 assembly…</div><div id="log" class="log"></div>
<div class="note">Reference hardware source: PRIAM's open F450 build lists Flamewheel F450, DJI 2312E 960KV motors, DJI 9450 props, APD 80A ESCs, Pixhawk 2.1 CubeOrange, F9P RTK GPS, 915 MHz SiK telemetry and 4S 4500 mAh LiPo. Match the actual college BOM before procurement or build decisions.</div>
</aside></div>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"}}</script>
<script type="module">
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {CSS2DRenderer,CSS2DObject} from 'three/addons/renderers/CSS2DRenderer.js';
const $=id=>document.getElementById(id);const log=m=>{const e=$('log');e.innerHTML+='<div>'+new Date().toLocaleTimeString()+' · '+m+'</div>';e.scrollTop=e.scrollHeight};const status=(m,c)=>{$('status').textContent=m;$('status').className='status '+(c==='ok'?'good':c==='err'?'err':'')};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050a0f);scene.fog=new THREE.Fog(0x050a0f,20,70);const cam=new THREE.PerspectiveCamera(42,1,.05,180);cam.position.set(7.8,5.6,9.1);const renderer=new THREE.WebGLRenderer({canvas:$('c'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const labelRenderer=new CSS2DRenderer();labelRenderer.domElement.id='labels';labelRenderer.setSize(10,10);labelRenderer.domElement.style.position='absolute';labelRenderer.domElement.style.inset='0';labelRenderer.domElement.style.pointerEvents='none';$('view').appendChild(labelRenderer.domElement);
const ctl=new OrbitControls(cam,renderer.domElement);ctl.enableDamping=true;ctl.minDistance=4;ctl.maxDistance=32;ctl.target.set(0,1.2,0);scene.add(new THREE.HemisphereLight(0xc9e5ff,0x141b1f,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(8,12,6);sun.castShadow=true;scene.add(sun);scene.add(new THREE.GridHelper(34,17,0x183744,0x0d2631));
const root=new THREE.Group();root.position.y=2;scene.add(root);const frame=new THREE.Group();root.add(frame);const electronics=new THREE.Group();root.add(electronics);const signal=new THREE.Group();root.add(signal);
const M={carbon:new THREE.MeshStandardMaterial({color:0x11171b,metalness:.55,roughness:.3}),metal:new THREE.MeshStandardMaterial({color:0x30383e,metalness:.72,roughness:.25}),board:new THREE.MeshStandardMaterial({color:0x245b59,metalness:.16,roughness:.42}),blue:new THREE.MeshStandardMaterial({color:0x2e6789,metalness:.22,roughness:.36}),gold:new THREE.MeshStandardMaterial({color:0xb5781d,metalness:.38,roughness:.32}),red:new THREE.MeshStandardMaterial({color:0x9a3842,metalness:.2,roughness:.4}),prop:new THREE.MeshStandardMaterial({color:0xdfe6e9,metalness:.15,roughness:.32,transparent:true,opacity:.88})};
function box(w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}function cyl(r,h,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),m);o.castShadow=true;o.receiveShadow=true;return o}function label(parent,title,sub,color){const d=document.createElement('div');d.className='label';d.style.borderColor=color;d.innerHTML='<b>'+title+'</b><small>'+sub+'</small>';const l=new CSS2DObject(d);l.position.set(0,.18,0);parent.add(l)}
const plateA=box(2.9,.12,2.15,M.carbon);plateA.position.y=.02;frame.add(plateA);const plateB=box(2.55,.1,1.85,M.carbon);plateB.position.y=.48;frame.add(plateB);
const motors=[[-1.55,.25,-.95],[1.55,.25,-.95],[-1.55,.25,.95],[1.55,.25,.95]],rotors=[],escs=[];
for(let i=0;i<4;i++){const p=motors[i];const arm=cyl(.095,2.75,M.metal);arm.rotation.z=Math.PI/2;arm.rotation.y=Math.atan2(p[2],p[0]);arm.position.set(p[0]/2,.23,p[2]/2);frame.add(arm);const esc=box(.4,.14,.55,M.board);esc.position.set(p[0]*.74,.28,p[2]*.74);esc.userData.base=esc.position.clone();esc.userData.ex= new THREE.Vector3(p[0]*.85,1.05,p[2]*.85);frame.add(esc);escs.push(esc);label(esc,'ESC '+(i+1),'APD 80A reference','#35e2b3');const motor=cyl(.2,.2,M.metal);motor.position.set(p[0],.36,p[2]);motor.userData.base=motor.position.clone();motor.userData.ex=new THREE.Vector3(p[0]*1.15,1.5,p[2]*1.15);frame.add(motor);label(motor,'MOTOR '+(i+1),'DJI 2312E 960KV','#35e2b3');const rotor=new THREE.Group();rotor.position.set(p[0],.5,p[2]);rotor.userData.base=rotor.position.clone();rotor.userData.ex=new THREE.Vector3(p[0]*1.15,1.65,p[2]*1.15);rotor.userData.dir=i%2===0?1:-1;const hub=cyl(.07,.08,M.metal);rotor.add(hub);for(let j=0;j<2;j++){const b=box(.92,.035,.075,M.prop);b.position.y=.07;b.rotation.y=j*Math.PI/2;rotor.add(b)}frame.add(rotor);rotors.push(rotor)}
const battery=box(1.4,.42,.7,M.carbon);battery.position.set(0,-.72,0);battery.userData={base:battery.position.clone(),ex:new THREE.Vector3(-2.9,-.7,0)};electronics.add(battery);label(battery,'BATTERY','4S 4500 mAh LiPo reference','#ffb34c');const power=box(.78,.15,.52,M.gold);power.position.set(0,-.38,0);power.userData={base:power.position.clone(),ex:new THREE.Vector3(2.8,-.4,0)};electronics.add(power);label(power,'POWER MODULE / PDB','battery distribution','#ffb34c');const fc=box(.82,.18,.64,M.blue);fc.position.set(0,.82,0);fc.userData={base:fc.position.clone(),ex:new THREE.Vector3(0,2.7,0)};electronics.add(fc);label(fc,'PIXHAWK 2.1 / CUBEORANGE','ArduPilot flight controller','#68b8ff');const gps=cyl(.25,.1,M.blue);gps.position.set(0,1.4,0);gps.userData={base:gps.position.clone(),ex:new THREE.Vector3(0,3.9,0)};electronics.add(gps);label(gps,'GPS + COMPASS','F9P RTK reference','#68b8ff');const telem=box(.72,.16,.46,M.board);telem.position.set(.9,.78,.08);telem.userData={base:telem.position.clone(),ex:new THREE.Vector3(3,2.2,.2)};electronics.add(telem);label(telem,'915 MHz TELEMETRY','companion / link','#68b8ff');const servo=box(.34,.22,.28,M.red);servo.position.set(0,-.35,.88);servo.userData={base:servo.position.clone(),ex:new THREE.Vector3(-2.7,1,.9)};electronics.add(servo);label(servo,'PAYLOAD SERVO','health-kit release','#ff6875');const bay=box(.85,.3,.62,M.gold);bay.position.set(0,-.72,.86);bay.userData={base:bay.position.clone(),ex:new THREE.Vector3(-2.4,-.1,1)};electronics.add(bay);label(bay,'HEALTH KIT BAY','payload compartment','#ff6875');
function line(a,b,color){const g=new THREE.BufferGeometry().setFromPoints([a,b]);const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity:.7}));signal.add(l);return l}line(power.position,fc.position,0xffb34c);line(fc.position,gps.position,0x68b8ff);line(telem.position,fc.position,0x68b8ff);escs.forEach(e=>line(fc.position,e.position,0x35e2b3));line(fc.position,servo.position,0xff6875);escs.forEach(e=>line(power.position,e.position,0xffb34c));
let exploded=false,state='IDLE',rpm=0,last=null,lastState='IDLE',pulses=[];
function pulse(a,b,color){const p=new THREE.Mesh(new THREE.SphereGeometry(.055,10,10),new THREE.MeshBasicMaterial({color}));signal.add(p);pulses.push({p,a:a.clone(),b:b.clone(),t:0})}function pulseMission(s){pulses=[];if(['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].includes(s)){pulse(power.position,fc.position,0xffb34c);escs.forEach(e=>pulse(fc.position,e.position,0x35e2b3));pulse(telem.position,fc.position,0x68b8ff)}if(s==='DELIVERING')pulse(fc.position,servo.position,0xff6875)}
function setExploded(on){exploded=on;const objs=[battery,power,fc,gps,telem,servo,bay,...escs,...rotors];objs.forEach(o=>{const u=o.userData;if(!u||!u.base)return;const dest=on?u.ex:u.base;o.position.copy(dest)});$('explode').textContent=on?'ASSEMBLED VIEW':'EXPLODED VIEW';status(on?'Exploded engineering view':'Assembled aircraft view','ok')}
function apply(d){last=d;state=d.state||'IDLE';rpm=Number(d.motor_rpm||0);$('source').textContent=d.source==='simnet'?'SIMNET / HUB':'LIVE HUB';$('state').textContent=state;$('state').className='big '+(['TAKEOFF','ENROUTE','RTL','LANDING'].includes(state)?'warn':'ok');$('mission').textContent=d.mission_id||'—';$('speed').textContent=Number(d.speed_ms||0).toFixed(1)+' m/s';$('alt').textContent=Number(d.altitude_m||0).toFixed(1)+' m';$('rpm').textContent=Math.round(rpm);$('battery').textContent=d.battery_pct==null?'100%':Number(d.battery_pct).toFixed(0)+'%';const active=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].includes(state);$('esc').textContent=active?'4 ACTIVE':'READY';$('motors').textContent=active?'RUNNING':'OFF';$('props').textContent=active?'SPINNING':'STOPPED';$('link').textContent=state==='IDLE'?'STANDBY':'ACTIVE';$('fc').textContent=active?'COMMANDING':'STANDBY';$('ctrl').textContent=active?'PWM / DShot':'STANDBY';$('servo').textContent=state==='DELIVERING'?'OPEN':'CLOSED';['n1','n2','n3','n4'].forEach(id=>$(id).classList.remove('active'));if(state!=='IDLE')$('n1').classList.add('active');if(state!=='IDLE')$('n2').classList.add('active');if(active)$('n3').classList.add('active');if(['DELIVERING','RTL','LANDING','COMPLETED'].includes(state))$('n4').classList.add('active');const done={s1:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s2:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s3:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s4:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s5:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s6:['HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s7:['DELIVERING','RTL','LANDING','COMPLETED'],s8:['RTL','LANDING','COMPLETED'],s9:['RTL','LANDING','COMPLETED']};Object.keys(done).forEach(id=>$(id).className='step '+(done[id].includes(state)?'done':''));const a={ARMING:'s3',TAKEOFF:'s5',ENROUTE:'s6',HOVERING:'s6',DELIVERING:'s7',RTL:'s9',LANDING:'s9'}[state];if(a)$(a).className='step active';if(state!==lastState){log('STATE → '+state);lastState=state;pulseMission(state)}}
function poll(){fetch('/drone_state?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{apply(d);status('Connected to /drone_state','ok')}).catch(e=>{status('Hub error: '+e.message,'err')}).finally(()=>setTimeout(poll,700))}
$('live').onclick=()=>{log('LIVE HUB → reconnect');poll()};$('test').onclick=()=>{const b=$('test');b.disabled=true;status('Sending TEST DISTRESS…');fetch('/node-alert?node=WEB-HARDWARE&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()}).then(t=>{log('DISTRESS → '+t);status('Distress accepted','ok')}).catch(e=>{log('TRIGGER ERROR → '+e.message);status('Trigger failed: '+e.message,'err')}).finally(()=>setTimeout(()=>b.disabled=false,700))};$('explode').onclick=()=>setExploded(!exploded);$('assemble').onclick=()=>setExploded(false);
function resize(){const r=$('view').getBoundingClientRect();cam.aspect=r.width/r.height;cam.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);labelRenderer.setSize(r.width,r.height)}addEventListener('resize',resize);resize();setExploded(false);status('F450/CubeOrange assembly ready','ok');log('Engineering assembly loaded');poll();const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();const spin=rpm*Math.PI*2/60*dt*.7;rotors.forEach((r,i)=>r.rotation.y+=spin*r.userData.dir);pulses.forEach(p=>{p.t=(p.t+dt*1.2)%1;p.p.position.lerpVectors(p.a,p.b,p.t)});ctl.update();renderer.render(scene,cam);labelRenderer.render(scene,cam)}animate();
</script>
</body></html>'''
