"""Robust geographic drone flight viewer for the deployed VanniKawachh demo."""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Drone Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Widgets/widgets.css">
<style>
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#071018;color:#eaf4f8;font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 410px;height:100vh}#world{position:relative;min-width:0}#cesium{position:absolute;inset:0}
.top{position:absolute;z-index:20;left:12px;right:12px;top:12px;display:flex;justify-content:space-between}.pill{background:#07131ee8;border:1px solid #27414f;border-radius:20px;padding:8px 12px}.ok{color:#32e0b0}.warn{color:#ffb24a}.bad{color:#ff6875}
#side{background:#08131bf7;border-left:1px solid #27414f;padding:13px;overflow:auto}.title{font-size:20px;font-weight:900}.sub,.note{color:#8da6b4;font-size:10px;line-height:1.5}.card{background:#0c1b25;border:1px solid #27414f;border-radius:11px;padding:11px;margin:9px 0}.lab{font-size:10px;color:#8da6b4;font-weight:800;letter-spacing:.1em}.big{font-size:27px;font-weight:900;margin:3px 0}.row{display:flex;justify-content:space-between;margin:7px 0}.val{font-weight:800;text-align:right}.seq{display:grid;gap:4px}.step{padding:7px;border:1px solid #1d3440;border-radius:7px;color:#657b87}.step.active{background:#241d10;border-color:#8b6327;color:#ffdfa7;font-weight:800}.step.done{background:#0b211b;border-color:#286c5a;color:#acf3df}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#364a54;margin-right:7px}.step.active .dot{background:#ffb24a}.step.done .dot{background:#32e0b0}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.btn{width:100%;border:1px solid #27414f;background:#122432;color:#fff;padding:10px;border-radius:8px;font-weight:800;cursor:pointer}.btn:hover{filter:brightness(1.15)}.primary{background:#0e2b24;border-color:#286d5a}.warnBtn{background:#2a2113;border-color:#705126}
#log{height:100px;overflow:auto;background:#061018;border:1px solid #19303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb8c7}.badge{position:absolute;z-index:20;bottom:12px;left:12px;background:#07131ee8;border:1px solid #27414f;padding:7px 9px;border-radius:8px;font-size:10px}
@media(max-width:850px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:30;right:0;top:0;bottom:0;width:min(410px,94vw);box-shadow:-20px 0 40px #000b}}
</style></head><body>
<div id="app"><section id="world"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · AUTONOMOUS DRONE FLIGHT</div><div class="pill"><b id="source" class="ok">HUB CONNECTING…</b></div></div><div id="cesium"></div><div class="badge">MAP <b id="mapstatus">loading…</b></div></section>
<aside id="side"><div class="title">Drone Flight Simulator</div><div class="sub">This view is driven by the same deployed Wokwi/ESP32 → hub → SimDrone pipeline. The map, aircraft, telemetry and hardware sequence all consume one mission state.</div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude AGL</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Distance remaining</span><span id="dist" class="val">—</span></div><div class="row"><span>Real ETA</span><span id="eta" class="val">—</span></div><div class="row"><span>Simulation clock</span><span id="clock" class="val">1× real-time</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger received</div><div class="step" id="s2"><span class="dot"></span>Arm / spin four rotors</div><div class="step" id="s3"><span class="dot"></span>Takeoff</div><div class="step" id="s4"><span class="dot"></span>Navigate to distress GPS</div><div class="step" id="s5"><span class="dot"></span>Hover at incident</div><div class="step" id="s6"><span class="dot"></span>Open payload bay</div><div class="step" id="s7"><span class="dot"></span>Drop health kit</div><div class="step" id="s8"><span class="dot"></span>RTL / land</div></div></div>
<div class="card"><div class="lab">AIRCRAFT SYSTEMS</div><div class="row"><span>4 × BLDC / ESC</span><span id="motors" class="val ok">OFF</span></div><div class="row"><span>Flight controller</span><span class="val ok">CONNECTED</span></div><div class="row"><span>GPS / compass</span><span class="val ok">LOCKED</span></div><div class="row"><span>Companion / LoRa</span><span class="val ok">ONLINE</span></div><div class="row"><span>Camera</span><span id="cam" class="val ok">STANDBY</span></div><div class="row"><span>Payload servo</span><span id="servo" class="val">CLOSED</span></div><div class="row"><span>Health kit</span><span id="kit" class="val">SECURED</span></div></div>
<div class="card"><div class="lab">ON-BOARD CONNECTIONS</div><svg viewBox="0 0 390 145" style="width:100%;height:145px;background:#08131b;border:1px solid #223b49;border-radius:8px"><g fill="none" stroke="#536f7a" stroke-width="7" stroke-linecap="round"><path d="M145 65L50 28"/><path d="M245 65L340 28"/><path d="M145 82L50 120"/><path d="M245 82L340 120"/></g><g fill="#192a33" stroke="#6a8791"><circle cx="48" cy="28" r="15"/><circle cx="342" cy="28" r="15"/><circle cx="48" cy="120" r="15"/><circle cx="342" cy="120" r="15"/></g><rect x="160" y="48" width="70" height="50" rx="8" fill="#173c48" stroke="#32e0b0"/><text x="171" y="70" fill="#bed2d9" font-size="9" font-weight="800">FLIGHT</text><text x="167" y="84" fill="#bed2d9" font-size="9" font-weight="800">CONTROLLER</text><rect x="172" y="104" width="48" height="18" rx="4" fill="#3d2d17" stroke="#ffb24a"/><text x="181" y="117" fill="#bed2d9" font-size="8">LiPo</text><rect x="171" y="3" width="47" height="16" rx="4" fill="#113126" stroke="#32e0b0"/><text x="181" y="14" fill="#bed2d9" font-size="8">GPS</text><rect x="267" y="102" width="72" height="22" rx="4" fill="#172c3d" stroke="#69b5ff"/><text x="275" y="116" fill="#bed2d9" font-size="8">COMP / LoRa</text><rect x="206" y="126" width="76" height="16" rx="4" fill="#312517" stroke="#ffb24a"/><text x="219" y="138" fill="#bed2d9" font-size="8">SERVO + KIT</text></svg><div class="note">LiPo → ESC/motor power. GPS/compass → flight controller. Companion/LoRa → mission link. Servo → health-kit release.</div></div>
<div class="card"><div class="lab">CONTROL SIGNAL</div><div class="grid"><div class="val">ESP32 SENSOR</div><div class="val">HUB DISPATCH</div><div class="val">FLIGHT CONTROLLER</div><div class="val">ESCs + SERVO</div></div></div>
<div class="grid"><button class="btn primary" id="live">LIVE HUB</button><button class="btn" id="trigger">TEST HUB DISTRESS</button><button class="btn" id="fit">FIT MISSION</button><button class="btn warnBtn" id="reset">RESET</button></div>
<div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div><div class="note">The backend simulator now defaults to 1× wall-clock playback. The aircraft speed/position comes from geographic distance and the configured 15 m/s cruise speed.</div></aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Cesium.js"></script>
<script>
const $=id=>document.getElementById(id);const log=m=>{const e=$('log');e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};let viewer,aircraft,home,target,route,live=true,timer=null,lastMission=null,lastState='IDLE',last=null;
const model='https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone.glb';const fallback='https://cdn.jsdelivr.net/gh/CesiumGS/cesium@main/Apps/SampleData/models/CesiumDrone/CesiumDrone.glb';const P=(lat,lon,h=0)=>Cesium.Cartesian3.fromDegrees(+lon,+lat,+h);const fm=m=>m==null?'—':m<1000?Math.round(m)+' m':(m/1000).toFixed(2)+' km';const fs=s=>s==null?'—':s>=3600?Math.floor(s/3600)+'h '+Math.floor((s%3600)/60)+'m':s>=60?Math.floor(s/60)+'m '+Math.round(s%60)+'s':Math.round(s)+'s';
function bearing(a,b){const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))}
function addModel(uri){aircraft=viewer.entities.add({name:'VanniKawachh Drone',position:P(21.1188,79.0195),model:{uri,scale:1.7,minimumPixelSize:80,maximumScale:3000,clampAnimations:true},label:{text:'VanniKawachh',font:'12px sans-serif',fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-35)}});}
async function init(){viewer=new Cesium.Viewer('cesium',{animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,infoBox:false,selectionIndicator:false,fullscreenButton:false,shouldAnimate:false});viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors'}));viewer.scene.globe.enableLighting=true;try{const b=await Cesium.createOsmBuildingsAsync();viewer.scene.primitives.add(b);$('mapstatus').textContent='OSM 3D buildings';}catch(e){$('mapstatus').textContent='map online';log('3D building layer unavailable; keeping geographic map');}addModel(model);home=viewer.entities.add({name:'Drone base',position:P(21.1188,79.0195),point:{pixelSize:10,color:Cesium.Color.CYAN,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DRONE BASE',font:'11px sans-serif',fillColor:Cesium.Color.CYAN,style:Cesium.LabelStyle.FILL_AND_OUTLINE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,pixelOffset:new Cesium.Cartesian2(0,-12)}});target=viewer.entities.add({name:'Distress target',point:{pixelSize:13,color:Cesium.Color.RED,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DISTRESS',font:'11px sans-serif',fillColor:Cesium.Color.RED,style:Cesium.LabelStyle.FILL_AND_OUTLINE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,pixelOffset:new Cesium.Cartesian2(0,-13)}});route=viewer.entities.add({name:'Mission route',polyline:{positions:[],width:4,material:Cesium.Color.CYAN.withAlpha(.75)}});log('3D globe ready · connecting to deployed hub');poll();}
function apply(d){if(!d)return;last=d;const s=d.state||'IDLE';$('state').textContent=s;$('state').className='big '+(s==='FAILED'?'bad':(['TAKEOFF','ENROUTE','RTL'].includes(s)?'warn':'ok'));$('mission').textContent=d.mission_id||'—';$('gps').textContent=d.lat!=null?Number(d.lat).toFixed(5)+', '+Number(d.lon).toFixed(5):'—';$('speed').textContent=Number(d.speed_ms||0).toFixed(1)+' m/s';$('alt').textContent=Number(d.altitude_m||0).toFixed(1)+' m';$('dist').textContent=fm(d.distance_m);$('eta').textContent=fs(d.eta_reach_s);$('clock').textContent=(d.sim_time_accel||1)+'× '+(Number(d.sim_time_accel||1)===1?'real-time':'accelerated');$('motors').textContent=d.motors_active?'SPINNING':'OFF';$('cam').textContent=d.motors_active?'ACTIVE':'STANDBY';$('servo').textContent=s==='DELIVERING'?'OPEN':'CLOSED';$('kit').textContent=d.kit_dropped?'DROPPED':'SECURED';if(d.home){home.position=P(d.home[0],d.home[1]);}if(d.target){target.position=P(d.target[0],d.target[1]);route.polyline.positions=[P(d.home?.[0]??d.lat,d.home?.[1]??d.lon),P(d.target[0],d.target[1])];}if(d.lat!=null){const h=Number(d.altitude_m||0);aircraft.position=P(d.lat,d.lon,h);if(d.target)aircraft.orientation=Cesium.Transforms.headingPitchRollQuaternion(P(d.lat,d.lon,h),new Cesium.HeadingPitchRoll(bearing([d.lat,d.lon],d.target),0,0));}if(d.mission_id&&d.mission_id!==lastMission){lastMission=d.mission_id;viewer.trackedEntity=aircraft;log('MISSION '+d.mission_id+' · dispatched');}if(s!==lastState){lastState=s;log('STATE → '+s);if(s==='COMPLETED')viewer.trackedEntity=undefined;}steps(s);}
function steps(s){const ids=['s1','s2','s3','s4','s5','s6','s7','s8'];ids.forEach(id=>$(id).className='step');const done={s1:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s4:['HOVERING','DELIVERING','RTL','COMPLETED'],s5:['DELIVERING','RTL','COMPLETED'],s6:['RTL','COMPLETED'],s7:['RTL','COMPLETED'],s8:['COMPLETED']};for(const [id,a] of Object.entries(done))if(a.includes(s))$(id).className='step done';const active={TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8'}[s];if(active)$(active).className='step active';if(s==='DELIVERING')$('s7').className='step active';if(s==='COMPLETED')ids.forEach(id=>$(id).className='step done');}
function poll(){if(!live)return;fetch(location.origin+'/drone_state?ts='+Date.now(),{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('drone_state HTTP '+r.status);const d=await r.json();$('source').textContent='HUB ONLINE';$('source').className='ok';apply(d);timer=setTimeout(poll,500)}).catch(async e=>{try{const r=await fetch(location.origin+'/drones?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('drones HTTP '+r.status);const ds=await r.json();const d=ds.find(x=>!x.available)||ds[0];$('source').textContent='HUB ONLINE · fleet fallback';$('source').className='warn';if(d)apply(d);timer=setTimeout(poll,700)}catch(e2){$('source').textContent='HUB ERROR · '+e2.message;$('source').className='bad';log('Hub read failed: '+e2.message);timer=setTimeout(poll,1500)}})}
$('live').onclick=()=>{live=true;log('LIVE HUB re-enabled');poll()};$('fit').onclick=()=>{if(last?.target) viewer.flyTo(route,{duration:1.5,offset:new Cesium.HeadingPitchRange(0,Cesium.Math.toRadians(-35),12000)});else viewer.flyTo(home,{duration:1})};$('reset').onclick=()=>{viewer.trackedEntity=undefined;viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(79.0889,21.1466,25000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-55),roll:0},duration:1.2})};$('trigger').onclick=async()=>{try{const r=await fetch(location.origin+'/node-alert?node=DRONE-SIM&lat=21.12800&lon=79.04700&event=1&conf=0.99&pir=1&light=30',{method:'POST'});if(!r.ok)throw new Error('trigger HTTP '+r.status);log('TEST DISTRESS accepted');live=true;poll()}catch(e){log('Trigger failed: '+e.message)}};
init();
</script></body></html>'''
