"""Professional Wokwi-style physical drone hardware view."""
from fastapi.responses import HTMLResponse

def attach(app):
    @app.get("/drone-hardware", response_class=HTMLResponse)
    def drone_hardware_page():
        return HTML

HTML=r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VanniKawachh | Drone Hardware</title>
<style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#050b10;color:#edf7fa;font:12px Segoe UI,Arial}#app{display:grid;grid-template-columns:minmax(0,1fr) 420px;height:100vh}#view{position:relative}#c{width:100%;height:100%;display:block}.top{position:absolute;z-index:3;left:12px;right:12px;top:12px;display:flex;justify-content:space-between}.pill{background:#07131eee;border:1px solid #284452;border-radius:12px;padding:8px 11px}.side{overflow:auto;background:#07121bf8;border-left:1px solid #284452;padding:12px}.title{font-size:21px;font-weight:900}.sub,.note{font-size:10px;color:#91a7b3;line-height:1.5}.card{border:1px solid #284452;border-radius:10px;background:#0b1a24;padding:10px;margin:8px 0}.lab{font-size:9px;letter-spacing:.1em;color:#91a7b3;font-weight:900}.big{font-size:26px;font-weight:900}.ok{color:#35e2b3}.warn{color:#ffb34c}.row{display:flex;justify-content:space-between;margin:6px 0}.val{font-weight:800}.seq{display:grid;gap:4px}.step{padding:6px 8px;border:1px solid #1d3440;border-radius:7px;color:#6d828d}.step.done{background:#0c211b;border-color:#2b6b5a;color:#b0f5e3}.step.active{background:#211a10;border-color:#8f6527;color:#ffe0a0}.btns{display:grid;grid-template-columns:1fr 1fr;gap:6px}.btn{padding:9px;border-radius:8px;border:1px solid #284452;background:#122431;color:#fff;font-weight:800;cursor:pointer}.btn.primary{background:#0d2d25;border-color:#286b5a}.status{margin-top:8px;padding:8px;border:1px solid #284452;border-radius:8px}.err{border-color:#913443;color:#ffbac1}.okbox{border-color:#286b5a;color:#b0f5e3}.legend{display:grid;grid-template-columns:1fr 1fr;gap:5px;font-size:9px}.legend div{padding:6px;border:1px solid #284452;border-radius:6px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:5px}.p{background:#ffb34c}.d{background:#68b8ff}.ctrl{background:#35e2b3}.pay{background:#ff6875}.log{height:80px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px monospace}
</style></head><body><div id="app"><section id="view"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · PHYSICAL DRONE / CIRCUIT SIM</div><div class="pill">SOURCE: <b id="src">CHECKING</b></div></div><canvas id="c"></canvas></section><aside class="side"><div class="title">On-Board Hardware</div><div class="sub">Direct GLB aircraft shell plus independently simulated Pixhawk, battery, PDB, GPS, ESCs, motors, propellers, companion link and payload hardware. No cross-origin Sketchfab iframe.</div><div class="card"><div class="lab">LIVE MISSION</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Motor RPM</span><span id="rpm" class="val">0</span></div></div><div class="card"><div class="lab">POWER PATH</div><div class="row"><span>LiPo → PDB</span><span class="val warn">POWER</span></div><div class="row"><span>PDB → ESC ×4</span><span id="esc" class="val">READY</span></div><div class="row"><span>ESC → BLDC ×4</span><span id="motors" class="val">OFF</span></div></div><div class="card"><div class="lab">CONTROL / DATA</div><div class="row"><span>GPS + compass + IMU → Pixhawk</span><span class="val">DATA</span></div><div class="row"><span>ESP32 → Hub → Companion</span><span id="link" class="val">STANDBY</span></div><div class="row"><span>Companion → Pixhawk</span><span id="fc" class="val">STANDBY</span></div><div class="row"><span>Pixhawk → ESC control</span><span id="ctrl" class="val">STANDBY</span></div><div class="row"><span>Servo → payload bay</span><span id="servo" class="val">CLOSED</span></div></div><div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div id="s1" class="step">Distress received</div><div id="s2" class="step">Link / mission command</div><div id="s3" class="step">Pixhawk armed</div><div id="s4" class="step">ESCs commanded</div><div id="s5" class="step">Four props spinning</div><div id="s6" class="step">Flight / hover</div><div id="s7" class="step">Payload servo opens</div><div id="s8" class="step">Health kit released</div><div id="s9" class="step">RTL / landing</div></div></div><div class="card"><div class="lab">SIGNAL LEGEND</div><div class="legend"><div><span class="dot p"></span>Power</div><div><span class="dot d"></span>Sensor/data</div><div><span class="dot ctrl"></span>Control</div><div><span class="dot pay"></span>Payload</div></div></div><div class="btns"><button id="live" class="btn primary">LIVE HUB</button><button id="test" class="btn">TEST DISTRESS</button><button id="explode" class="btn">EXPLODED WIRING</button><button id="assemble" class="btn">ASSEMBLED DRONE</button></div><div id="status" class="status">Starting 3D hardware…</div><div id="log" class="log"></div></aside></div>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"}}</script>
<script type="module">
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id); const canvas=$('c');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x050b10); scene.fog=new THREE.Fog(0x050b10,20,70);
const camera=new THREE.PerspectiveCamera(45,1,.1,200); camera.position.set(8,6,10);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true;
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0xbddfff,0x162329,2.2)); const sun=new THREE.DirectionalLight(0xffffff,3); sun.position.set(7,12,6); sun.castShadow=true; scene.add(sun); scene.add(new THREE.GridHelper(36,24,0x163442,0x0d2530));
const root=new THREE.Group(); root.position.y=1.8; scene.add(root); const cad=new THREE.Group(); root.add(cad); const shell=new THREE.Group(); root.add(shell);
const mat=(c,m=.2,r=.45)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});
const dark=mat(0x1c252b,.65,.28), pcb=mat(0x174b45,.25,.4), blue=mat(0x2b5d7b,.3,.35), orange=mat(0xb57722,.2,.38), silver=mat(0x7d8d94,.8,.25), red=mat(0x8e323a,.25,.4);
function box(w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const battery=box(1.6,.48,.8,orange); battery.position.set(0,-.65,0); cad.add(battery); const pdb=box(.9,.16,.65,pcb); pdb.position.set(0,-.15,0); cad.add(pdb);
const fc=box(.9,.16,.7,pcb); fc.position.set(0,.45,0); cad.add(fc); const gps=box(.42,.12,.42,blue); gps.position.set(0,1.02,0); cad.add(gps); const companion=box(.7,.18,.48,blue); companion.position.set(.9,.35,0); cad.add(companion); const servo=box(.5,.18,.35,red); servo.position.set(0,-.3,.92); cad.add(servo);
const payload=box(.45,.3,.4,orange); payload.position.set(0,-.67,.92); payload.visible=false; cad.add(payload);
const motorPos=[[-2.2,.75,-1.2],[2.2,.75,-1.2],[-2.2,.75,1.2],[2.2,.75,1.2]]; const rotors=[]; const escs=[];
motorPos.forEach((p,i)=>{const arm=box(2.6,.12,.16,dark); arm.position.set((p[0])/2,.22,p[2]/2); arm.rotation.y=Math.atan2(p[2],p[0]); cad.add(arm); const esc=box(.42,.16,.55,pcb); esc.position.set(p[0]*.72,.22,p[2]*.72); cad.add(esc); escs.push(esc); const g=new THREE.Group(); g.position.set(p[0],.32,p[2]); const body=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.16,24),dark); body.rotation.x=Math.PI/2; g.add(body); const prop=new THREE.Group(); prop.position.y=.14; for(let k=0;k<2;k++){const blade=box(.9,.035,.09,silver); blade.rotation.y=k*Math.PI/2; prop.add(blade)} g.add(prop); cad.add(g); rotors.push(prop)});
const frame=box(3.6,.28,2.5,dark); frame.position.y=.05; cad.add(frame);
let glb=null; new GLTFLoader().load('https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone_nologo.glb',g=>{glb=g.scene; glb.scale.setScalar(2.5); const b=new THREE.Box3().setFromObject(glb); const c=b.getCenter(new THREE.Vector3()); glb.position.sub(c); glb.position.y=.15; glb.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}}); shell.add(glb); log('Loaded direct GLB aircraft shell')},undefined,()=>log('Direct GLB unavailable; CAD assembly remains active'));
const paths=[]; function path(a,b,color){const geo=new THREE.BufferGeometry().setFromPoints([a,b]); const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity:.55})); cad.add(line); return line}
paths.push(path(new THREE.Vector3(0,-.65,0),new THREE.Vector3(0,-.15,0),0xffb34c)); paths.push(path(new THREE.Vector3(0,-.15,0),new THREE.Vector3(0,.45,0),0x35e2b3)); paths.push(path(new THREE.Vector3(.9,.35,0),new THREE.Vector3(0,.45,0),0x68b8ff)); escs.forEach(e=>paths.push(path(new THREE.Vector3(0,.45,0),e.position,0x35e2b3))); paths.push(path(new THREE.Vector3(0,.45,0),new THREE.Vector3(0,-.3,.92),0xff6875));
const pulses=[]; function pulse(a,b,color){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,12,12),new THREE.MeshBasicMaterial({color})); cad.add(m); pulses.push({m,a:a.clone(),b:b.clone(),t:0});}
function pulseSet(active){if(!active)return; pulse(new THREE.Vector3(0,-.65,0),new THREE.Vector3(0,-.15,0),0xffb34c); pulse(new THREE.Vector3(.9,.35,0),new THREE.Vector3(0,.45,0),0x68b8ff); escs.forEach(e=>pulse(new THREE.Vector3(0,.45,0),e.position,0x35e2b3)); if(last&&last.state==='DELIVERING')pulse(new THREE.Vector3(0,.45,0),new THREE.Vector3(0,-.3,.92),0xff6875)}
let exploded=false,last=null,lastState='IDLE'; function setView(x){exploded=x; shell.visible=!x; cad.children.forEach(o=>{if(o===frame||o===battery||o===pdb||o===fc||o===gps||o===companion||o===servo||o===payload||escs.includes(o)||rotors.some(r=>r===o)){} }); if(x){frame.position.y=-.2;battery.position.y=-1.4;pdb.position.y=-.6;fc.position.y=.7;gps.position.y=1.55;companion.position.x=2.0;servo.position.z=1.6;payload.visible=true;motorPos.forEach((p,i)=>{escs[i].position.set(p[0]*.9,.1,p[2]*.9);rotors[i].parent.position.set(p[0]*1.35,.2,p[2]*1.35)}); $('explode').textContent='ASSEMBLED'}else{frame.position.y=.05;battery.position.y=-.65;pdb.position.y=-.15;fc.position.y=.45;gps.position.y=1.02;companion.position.x=.9;servo.position.z=.92;payload.visible=false;motorPos.forEach((p,i)=>{escs[i].position.set(p[0]*.72,.22,p[2]*.72);rotors[i].parent.position.set(p[0],.32,p[2])}); $('explode').textContent='EXPLODED WIRING'}}
function apply(d){last=d; const s=d.state||'IDLE'; $('src').textContent='LIVE HUB'; $('state').textContent=s; $('state').className='big '+(['TAKEOFF','ENROUTE','RTL','LANDING'].includes(s)?'warn':'ok'); $('mission').textContent=d.mission_id||'—'; $('speed').textContent=Number(d.speed_ms||0).toFixed(1)+' m/s'; $('alt').textContent=Number(d.altitude_m||0).toFixed(1)+' m'; $('rpm').textContent=Math.round(Number(d.motor_rpm||0)); const active=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].includes(s); $('esc').textContent=active?'4 ACTIVE':'READY'; $('motors').textContent=active?'RUNNING':'OFF'; $('link').textContent=s==='IDLE'?'STANDBY':'ACTIVE'; $('fc').textContent=active?'COMMANDING':'STANDBY'; $('ctrl').textContent=active?'PWM / DShot':'STANDBY'; $('servo').textContent=s==='DELIVERING'?'OPEN':'CLOSED'; const done={s1:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s2:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s3:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s4:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s5:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s6:['HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s7:['DELIVERING','RTL','LANDING','COMPLETED'],s8:['RTL','LANDING','COMPLETED'],s9:['RTL','LANDING','COMPLETED']}; Object.keys(done).forEach(id=>$(id).className='step'+(done[id].includes(s)?' done':'')); const activeId={ARMING:'s3',TAKEOFF:'s4',ENROUTE:'s5',HOVERING:'s6',DELIVERING:'s7',RTL:'s9',LANDING:'s9'}[s]; if(activeId)$(activeId).className='step active'; if(s!==lastState){log('STATE → '+s);lastState=s} pulseSet(active); }
function log(m){$('log').innerHTML+='<div>'+new Date().toLocaleTimeString()+' · '+m+'</div>'; $('log').scrollTop=$('log').scrollHeight}
let timer; function poll(){fetch('/drone_state?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(apply).then(()=>{$('status').textContent='Connected to /drone_state';$('status').className='status okbox'}).catch(e=>{$('src').textContent='HUB ERROR';$('status').textContent='Hub error: '+e.message;$('status').className='status err'}).finally(()=>timer=setTimeout(poll,700))}
$('live').onclick=()=>{log('LIVE HUB → connect');poll()}; $('test').onclick=()=>{const b=$('test');b.disabled=true;$('status').textContent='Sending TEST DISTRESS…';fetch('/node-alert?node=WEB-HARDWARE&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()}).then(t=>{log('DISTRESS → '+t)}).catch(e=>{log('TRIGGER ERROR → '+e.message);$('status').textContent='Trigger failed: '+e.message;$('status').className='status err'}).finally(()=>setTimeout(()=>b.disabled=false,700))}; $('explode').onclick=()=>setView(!exploded); $('assemble').onclick=()=>setView(false);
function resize(){const r=document.getElementById('view').getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)} addEventListener('resize',resize); resize(); setView(false); log('Hardware simulator ready'); poll();
let clock=new THREE.Clock(); function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();const rpm=Number(last?.motor_rpm||0);const speed=rpm*dt*0.0007;rotors.forEach((p,i)=>p.rotation.y+=(i%2?1:-1)*speed); pulses.forEach(p=>{p.t+=dt*1.5;if(p.t>1)p.t=0;p.m.position.lerpVectors(p.a,p.b,p.t)});controls.update();renderer.render(scene,camera)} animate();
</script></body></html>'''
