"""Professional physical-hardware view for VanniKawachh.

This page is deliberately separate from the geographic flight viewer. It uses a
real Sketchfab 3D aircraft viewer supplied by the project owner and a precise
engineering wiring diagram for the proposed Pixhawk/ArduPilot quadcopter.
The mission state comes from the same /drone_state feed as the Wokwi -> hub path.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-hardware", response_class=HTMLResponse)
    def drone_hardware_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Drone Hardware Architecture</title>
<style>
:root{--bg:#050a0f;--panel:#0a151e;--line:#294452;--txt:#edf7fa;--muted:#8ea6b4;--power:#ffb34c;--data:#66b8ff;--ctrl:#34e2b3;--payload:#ff6e79;--ok:#34e2b3;--bad:#ff6875}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 500px;width:100vw;height:100vh}
#model{position:relative;min-width:0;background:#04090d}.modelFrame{position:absolute;inset:0}.modelFrame iframe{width:100%;height:100%;border:0;background:#04090d}.top{position:absolute;z-index:5;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;pointer-events:none}.pill{background:#07131ee8;border:1px solid var(--line);border-radius:999px;padding:8px 12px;backdrop-filter:blur(8px)}.pill b{color:#fff}
#engineering{position:absolute;inset:0;background:linear-gradient(180deg,#071017,#03080c);display:none;padding:30px}.engineering-show{display:block}.engTitle{font-size:23px;font-weight:900;margin-bottom:4px}.engSub{color:var(--muted);font-size:11px;margin-bottom:12px}.scheme{position:relative;width:100%;height:calc(100% - 56px);border:1px solid var(--line);border-radius:14px;background:#07131b;overflow:hidden}.grid{position:absolute;inset:0;background-image:linear-gradient(#12303d 1px,transparent 1px),linear-gradient(90deg,#12303d 1px,transparent 1px);background-size:44px 44px;opacity:.28}.comp{position:absolute;border:1px solid #44606d;border-radius:10px;background:#0e202a;box-shadow:0 8px 24px #0008;padding:9px;text-align:center;font-weight:900}.comp small{display:block;margin-top:3px;color:var(--muted);font-size:9px;font-weight:700}.battery{left:6%;top:74%;width:20%;border-color:var(--power);color:var(--power)}.pdb{left:37%;top:74%;width:19%;border-color:var(--power);color:var(--power)}.fc{left:38%;top:36%;width:22%;border-color:var(--ctrl);color:var(--ctrl)}.gps{left:41%;top:9%;width:16%;border-color:var(--data);color:var(--data)}.companion{left:68%;top:30%;width:23%;border-color:var(--data);color:var(--data)}.esc1,.esc2,.esc3,.esc4{width:12%;border-color:#55717e}.esc1{left:5%;top:29%}.esc2{left:83%;top:29%}.esc3{left:5%;top:53%}.esc4{left:83%;top:53%}.motor1,.motor2,.motor3,.motor4{width:12%;border-color:#718894}.motor1{left:5%;top:14%}.motor2{left:83%;top:14%}.motor3{left:5%;top:80%}.motor4{left:83%;top:80%}.servo{left:68%;top:66%;width:23%;border-color:var(--payload);color:var(--payload)}.arrow{position:absolute;height:3px;border-radius:3px;transform-origin:left center;animation:flow 1.35s linear infinite}.powerLine{background:var(--power);color:var(--power)}.dataLine{background:var(--data);color:var(--data)}.ctrlLine{background:var(--ctrl);color:var(--ctrl)}.payloadLine{background:var(--payload);color:var(--payload)}@keyframes flow{0%{opacity:.25;box-shadow:0 0 0 transparent}45%{opacity:1;box-shadow:0 0 14px currentColor}100%{opacity:.25}}
#side{background:#07121bf8;border-left:1px solid var(--line);padding:13px;overflow:auto}.title{font-size:22px;font-weight:900}.sub,.note{font-size:10px;color:var(--muted);line-height:1.5}.card{background:linear-gradient(180deg,#0d1d27,#08131c);border:1px solid var(--line);border-radius:12px;padding:11px;margin:9px 0}.lab{font-size:10px;letter-spacing:.1em;color:var(--muted);font-weight:900}.big{font-size:28px;font-weight:900;margin:2px 0}.ok{color:var(--ok)}.bad{color:var(--bad)}.warn{color:var(--power)}.row{display:flex;justify-content:space-between;gap:12px;margin:7px 0}.val{font-weight:800;text-align:right}.power{color:var(--power)}.data{color:var(--data)}.ctrl{color:var(--ctrl)}.payload{color:var(--payload)}
.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;background:#09151d;color:#657d89}.step.active{border-color:#916729;background:#221a10;color:#ffdfa0;font-weight:800}.step.done{border-color:#286b5a;background:#0c211b;color:#aef4e1}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#3a4e57;margin-right:7px}.step.active .dot{background:var(--power)}.step.done .dot{background:var(--ok)}
.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:3px;align-items:center}.node{padding:8px 3px;text-align:center;font-size:8px;border:1px solid #2b4553;border-radius:7px;background:#0a1922}.node.active{border-color:var(--ok);box-shadow:0 0 12px #34e2b322}.arr{color:var(--ok)}
.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);border-radius:8px;padding:10px;background:#112432;color:#fff;font-weight:900;cursor:pointer}.btn.primary{background:#0d2c24;border-color:#286b5a}.btn.warn{background:#291d10;border-color:#6f4f24}.btn:disabled{opacity:.45;cursor:wait}.btn:hover:not(:disabled){filter:brightness(1.12)}
.status{padding:8px 10px;border-radius:8px;background:#061016;border:1px solid #1c3744;font-size:10px;min-height:18px}.status.ok{border-color:#286b5a;color:#aef4e1}.status.err{border-color:#8f3543;color:#ffb8c0}.status.busy{border-color:#916729;color:#ffdfa0}
#log{height:90px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb9c7}.credit a{color:var(--data)}
@media(max-width:980px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:20;right:0;top:0;bottom:0;width:min(500px,96vw);box-shadow:-20px 0 50px #000c}}
</style></head><body>
<div id="app"><section id="model"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · PHYSICAL DRONE / CIRCUIT SIM</div><div class="pill">SOURCE: <b id="source">CHECKING…</b></div></div>
<div class="modelFrame"><iframe id="sketch" title="3D drone model" allow="autoplay; fullscreen; xr-spatial-tracking; accelerometer; gyroscope" src="https://sketchfab.com/models/d38af0afb72343f69eed6da6457df11b/embed?autostart=1&ui_controls=1&ui_infos=0&ui_inspector=0&ui_stop=0&ui_watermark=1"></iframe></div>
<div id="engineering"><div class="engTitle">Exploded Engineering Connection View</div><div class="engSub">Power, sensor/data, motor-control and payload-actuation paths for the proposed Pixhawk / ArduPilot quadcopter.</div><div class="scheme"><div class="grid"></div>
<div class="comp gps">GPS + COMPASS<small>GPS / sensor data</small></div><div class="comp fc">PIXHAWK / ARDUPILOT<small>Flight controller</small></div><div class="comp companion">COMPANION / LoRa-WiFi<small>Mission + telemetry</small></div><div class="comp battery">LiPo BATTERY<small>Aircraft power</small></div><div class="comp pdb">PDB / POWER MODULE<small>Power distribution</small></div><div class="comp esc1">ESC 1<small>Motor 1</small></div><div class="comp esc2">ESC 2<small>Motor 2</small></div><div class="comp esc3">ESC 3<small>Motor 3</small></div><div class="comp esc4">ESC 4<small>Motor 4</small></div><div class="comp motor1">M1 / PROP 1<small>CW / CCW by frame</small></div><div class="comp motor2">M2 / PROP 2<small>Opposing rotation</small></div><div class="comp motor3">M3 / PROP 3<small>Opposing rotation</small></div><div class="comp motor4">M4 / PROP 4<small>Opposing rotation</small></div><div class="comp servo">SERVO + HEALTH KIT<small>Payload release</small></div>
<div class="arrow dataLine" style="left:49%;top:25%;width:12%;transform:rotate(90deg)"></div><div class="arrow dataLine" style="left:60%;top:45%;width:14%;transform:rotate(-10deg)"></div><div class="arrow ctrlLine" style="left:50%;top:55%;width:35%;transform:rotate(-20deg)"></div><div class="arrow ctrlLine" style="left:50%;top:57%;width:37%;transform:rotate(20deg)"></div><div class="arrow ctrlLine" style="left:50%;top:59%;width:37%;transform:rotate(-58deg)"></div><div class="arrow ctrlLine" style="left:50%;top:60%;width:37%;transform:rotate(58deg)"></div><div class="arrow powerLine" style="left:27%;top:82%;width:14%"></div><div class="arrow powerLine" style="left:56%;top:83%;width:27%;transform:rotate(180deg)"></div><div class="arrow payloadLine" style="left:58%;top:76%;width:13%;transform:rotate(12deg)"></div>
</div></div></section>
<aside id="side"><div class="title">Real Aircraft Integration</div><div class="sub">3D aircraft on the left; engineering wiring on demand. Both are driven by the same deployed mission state. This is the Wokwi-equivalent screen for the drone electronics.</div>
<div class="card"><div class="lab">LIVE SYSTEM</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Hub</span><span id="hub" class="val">CHECKING</span></div></div>
<div class="card"><div class="lab">REAL HARDWARE PATH</div><div class="row"><span>LiPo → PDB / power module</span><span class="val power">POWER</span></div><div class="row"><span>PDB → ESC ×4</span><span id="esc" class="val">READY</span></div><div class="row"><span>ESC → BLDC motors ×4</span><span id="motors" class="val">STOPPED</span></div><div class="row"><span>GPS + compass + IMU → Pixhawk</span><span class="val data">DATA</span></div><div class="row"><span>Pixhawk → ESC control</span><span id="ctrl" class="val ctrl">STANDBY</span></div><div class="row"><span>Companion / LoRa → mission</span><span id="link" class="val data">STANDBY</span></div><div class="row"><span>Servo → health-kit bay</span><span id="servo" class="val payload">CLOSED</span></div></div>
<div class="card"><div class="lab">MISSION / ACTUATORS</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress received</div><div class="step" id="s2"><span class="dot"></span>Mission command / link</div><div class="step" id="s3"><span class="dot"></span>Pixhawk armed</div><div class="step" id="s4"><span class="dot"></span>ESCs commanded</div><div class="step" id="s5"><span class="dot"></span>Four propellers spinning</div><div class="step" id="s6"><span class="dot"></span>Flight / hover</div><div class="step" id="s7"><span class="dot"></span>Payload servo opens</div><div class="step" id="s8"><span class="dot"></span>Health kit released</div><div class="step" id="s9"><span class="dot"></span>RTL / landing</div></div></div>
<div class="card"><div class="lab">CONTROL CHAIN</div><div class="chain"><div id="n1" class="node">ESP32<br>SENSOR</div><div class="arr">→</div><div id="n2" class="node">HUB<br>DISPATCH</div><div class="arr">→</div><div id="n3" class="node">PIXHAWK<br>ARDUPILOT</div><div class="arr">→</div><div id="n4" class="node">ESCs<br>+ SERVO</div></div></div>
<div class="buttons"><button id="live" class="btn primary">LIVE HUB</button><button id="trigger" class="btn">TEST DISTRESS</button><button id="assembled" class="btn">3D AIRCRAFT</button><button id="exploded" class="btn warn">EXPLODED WIRING</button></div>
<div id="status" class="status">Initializing hub connection…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div><div class="note credit">3D model: <a href="https://sketchfab.com/3d-models/inside-drone-d38af0afb72343f69eed6da6457df11b" target="_blank" rel="noopener">Inside Drone</a>. Engineering wiring follows the Pixhawk/ArduPilot connection model; exact motor numbering/direction must match the selected X-frame configuration.</div></aside></div>
<script>
(function(){
const $=id=>document.getElementById(id);const log=m=>{const e=$("log");e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};let live=true,lastState="IDLE",lastMission=null,pollTimer=null;
function status(text,kind){const e=$("status");e.textContent=text;e.className="status"+(kind?" "+kind:"")}
function setState(d){if(!d)return;const s=d.state||"IDLE";$("state").textContent=s;$("state").className="big "+(s==="FAILED"?"bad":(["TAKEOFF","ENROUTE","RTL","LANDING"].includes(s)?"warn":"ok"));$("mission").textContent=d.mission_id||"—";$("gps").textContent=d.lat!=null?`${Number(d.lat).toFixed(5)}, ${Number(d.lon).toFixed(5)}`:"—";$("speed").textContent=`${Number(d.speed_ms||d.ground_speed_ms||0).toFixed(1)} m/s`;$("alt").textContent=`${Number(d.altitude_m||0).toFixed(1)} m`;const armed=["TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING"].includes(s);$("esc").textContent=armed?"4 ACTIVE":"READY";$("motors").textContent=armed?"RUNNING":"STOPPED";$("ctrl").textContent=armed?"ACTIVE":"STANDBY";$("link").textContent=s==="IDLE"?"STANDBY":"ACTIVE";$("servo").textContent=s==="DELIVERING"?"OPEN":"CLOSED";const done={s1:["ARMING","TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s2:["ARMING","TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s3:["TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s4:["ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s5:["TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING"],s6:["HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s7:["DELIVERING","RTL","LANDING","COMPLETED"],s8:["RTL","LANDING","COMPLETED"],s9:["RTL","LANDING","COMPLETED"]};Object.entries(done).forEach(([id,list])=>$(id).className="step"+(list.includes(s)?" done":""));const active={ARMING:"s3",TAKEOFF:"s4",ENROUTE:"s5",HOVERING:"s6",DELIVERING:"s7",RTL:"s9",LANDING:"s9"}[s];if(active)$(active).className="step active";["n1","n2","n3","n4"].forEach(id=>$(id).classList.remove("active"));if(s!=="IDLE")$("n1").classList.add("active");if(s!=="IDLE")$("n2").classList.add("active");if(armed)$("n3").classList.add("active");if(["DELIVERING","RTL","LANDING","COMPLETED"].includes(s))$("n4").classList.add("active");if(s!==lastState){log(`STATE → ${s}`);lastState=s}if(d.mission_id&&d.mission_id!==lastMission){lastMission=d.mission_id;log(`MISSION ${d.mission_id}`)}}
async function readHub(){try{const r=await fetch("/drone_state?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();$("hub").textContent="ONLINE";$("source").textContent="LIVE HUB";status("Connected to deployed /drone_state","ok");setState(d);return true}catch(e){$("hub").textContent="OFFLINE";$("source").textContent="HUB ERROR";status(`Hub error: ${e.message}`,"err");return false}}
function poll(){if(!live)return;readHub().finally(()=>{pollTimer=setTimeout(poll,700)})}
$("live").onclick=async()=>{live=true;status("Connecting to deployed hub…","busy");log("LIVE HUB → checking /drone_state");const ok=await readHub();if(ok)log("LIVE HUB → connected");poll()};
$("trigger").onclick=async()=>{const b=$("trigger");b.disabled=true;status("Sending TEST DISTRESS to /node-alert…","busy");log("TEST DISTRESS → /node-alert");try{const r=await fetch(`/node-alert?node=WEB-HARDWARE&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30`,{method:"GET",cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${text}`);log("HUB RESPONSE → "+text);status("Distress accepted — waiting for mission state","ok");live=true;poll()}catch(e){status(`Trigger failed: ${e.message}`,"err");log("TRIGGER ERROR → "+e.message)}finally{setTimeout(()=>b.disabled=false,700)}};
$("assembled").onclick=()=>{$("engineering").classList.remove("engineering-show");status("3D aircraft view — rotate/zoom the real model","ok");log("VIEW → 3D AIRCRAFT")};$("exploded").onclick=()=>{$("engineering").classList.add("engineering-show");status("Engineering wiring view — power/data/control paths","ok");log("VIEW → EXPLODED WIRING")};
log("Hardware page ready");readHub().finally(poll);
})();
</script></body></html>'''
