"""Stable Cesium geographic flight simulator for VanniKawachh.

This is intentionally conservative: one Cesium globe, one aircraft entity, explicit
route geometry, and manual camera control. It does not use trackedEntity or 3D
Tiles buildings because those were causing the previous renderer crash when a
mission changed state.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Autonomous Drone Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Widgets/widgets.css">
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#071018;color:#eaf4f8;font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 410px;height:100vh}#world{position:relative;min-width:0}#cesium{position:absolute;inset:0}
.top{position:absolute;z-index:20;left:12px;right:12px;top:12px;display:flex;justify-content:space-between;pointer-events:none}.pill{background:#07131ee8;border:1px solid #27414f;border-radius:20px;padding:8px 12px}.ok{color:#32e0b0}.warn{color:#ffb24a}.bad{color:#ff6875}
#side{background:#08131bf7;border-left:1px solid #27414f;padding:13px;overflow:auto}.title{font-size:20px;font-weight:900}.sub,.note{color:#8da6b4;font-size:10px;line-height:1.5}.card{background:#0c1b25;border:1px solid #27414f;border-radius:11px;padding:11px;margin:9px 0}.lab{font-size:10px;color:#8da6b4;font-weight:800;letter-spacing:.1em}.big{font-size:27px;font-weight:900;margin:3px 0}.row{display:flex;justify-content:space-between;margin:7px 0}.val{font-weight:800;text-align:right}.seq{display:grid;gap:4px}.step{padding:7px;border:1px solid #1d3440;border-radius:7px;color:#657b87}.step.active{background:#241d10;border-color:#8b6327;color:#ffdfa7;font-weight:800}.step.done{background:#0b211b;border-color:#286c5a;color:#acf3df}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#364a54;margin-right:7px}.step.active .dot{background:#ffb24a}.step.done .dot{background:#32e0b0}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.btn{width:100%;border:1px solid #27414f;background:#122432;color:#fff;padding:10px;border-radius:8px;font-weight:800;cursor:pointer}.btn:hover{filter:brightness(1.15)}.primary{background:#0e2b24;border-color:#286d5a}.warnBtn{background:#2a2113;border-color:#705126}
#log{height:110px;overflow:auto;background:#061018;border:1px solid #19303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb8c7}.badge{position:absolute;z-index:20;bottom:12px;left:12px;background:#07131ee8;border:1px solid #27414f;padding:7px 9px;border-radius:8px;font-size:10px}
#hud{position:absolute;z-index:15;left:14px;top:68px;pointer-events:none}.hud{background:#07131ed9;border:1px solid #27414f;border-radius:8px;padding:9px;min-width:190px}.hud b{font-size:18px}.reticle{position:absolute;z-index:10;left:50%;top:50%;width:44px;height:44px;transform:translate(-50%,-50%);border:1px solid #8fe7ff80;border-radius:50%;pointer-events:none}.reticle:before,.reticle:after{content:"";position:absolute;background:#8fe7ff80}.reticle:before{width:64px;height:1px;left:-11px;top:21px}.reticle:after{height:64px;width:1px;left:21px;top:-11px}
@media(max-width:850px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:30;right:0;top:0;bottom:0;width:min(410px,94vw);box-shadow:-20px 0 40px #000b}}
</style></head><body>
<div id="app"><section id="world">
<div class="top"><div class="pill"><b>VANNIKAWACHH</b> · AUTONOMOUS DRONE FLIGHT</div><div class="pill"><b id="source" class="ok">HUB CHECKING</b></div></div>
<div id="cesium"></div><div class="reticle"></div>
<div id="hud"><div class="hud"><div style="font-size:9px;color:#8da6b4">FLIGHT HUD</div><b id="hudState">IDLE</b><div>SPD <span id="hudSpeed">0.0</span> m/s · ALT <span id="hudAlt">0.0</span> m</div><div>V/S <span id="hudVs">0.0</span> m/s · RPM <span id="hudRpm">0</span></div><div>HDG <span id="hudHeading">000</span>° · BAT <span id="hudBattery">100</span>%</div></div></div>
<div class="badge">MAP <b id="mapstatus">loading…</b> · Camera: drag/orbit · right-drag/pan · wheel/zoom</div>
</section>
<aside id="side"><div class="title">Drone Flight Simulator</div><div class="sub">Same deployed Wokwi/ESP32 → hub → SimDrone mission feed. Browser presentation layer; no SIMNET dependency.</div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude AGL</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>V/S</span><span id="vs" class="val">0.0 m/s</span></div><div class="row"><span>Heading</span><span id="heading" class="val">000°</span></div><div class="row"><span>Motor RPM</span><span id="rpm" class="val">0</span></div><div class="row"><span>Battery</span><span id="battery" class="val">100%</span></div><div class="row"><span>Distance</span><span id="dist" class="val">—</span></div><div class="row"><span>ETA</span><span id="eta" class="val">—</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger received</div><div class="step" id="s2"><span class="dot"></span>Arm / spin four rotors</div><div class="step" id="s3"><span class="dot"></span>Vertical takeoff</div><div class="step" id="s4"><span class="dot"></span>Navigate to distress GPS</div><div class="step" id="s5"><span class="dot"></span>Hover at incident</div><div class="step" id="s6"><span class="dot"></span>Open payload bay</div><div class="step" id="s7"><span class="dot"></span>Drop health kit</div><div class="step" id="s8"><span class="dot"></span>RTL / land</div></div></div>
<div class="card"><div class="lab">MISSION PLAN</div><div class="row"><span>HOME</span><span id="home" class="val">—</span></div><div class="row"><span>TARGET</span><span id="target" class="val">—</span></div><div class="row"><span>Current phase</span><span id="phase" class="val">IDLE</span></div></div>
<div class="card"><div class="lab">CONTROLS</div><div class="grid"><button class="btn primary" id="trigger">TEST DISTRESS</button><button class="btn" id="live">LIVE HUB</button><button class="btn" id="fit">FIT MISSION</button><button class="btn" id="topdown">TOP DOWN</button><button class="btn" id="follow">FOLLOW: OFF</button><button class="btn warnBtn" id="homeView">HOME VIEW</button></div></div>
<div id="status" class="card">Initialising Cesium…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div></aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Cesium.js"></script>
<script>
(() => {
'use strict';
const $=id=>document.getElementById(id); const safeNum=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const log=m=>{const e=$('log');e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};
const setStatus=(m,c='')=>{const e=$('status');e.textContent=m;e.style.borderColor=c==='err'?'#913443':c==='ok'?'#286c5a':'#27414f';e.style.color=c==='err'?'#ffbcc5':c==='ok'?'#acf3df':'#b8d0d9'};
const fmtD=m=>m==null?'—':m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`; const fmtT=s=>s==null?'—':s<60?`${Math.round(s)}s`:`${Math.floor(s/60)}m ${Math.round(s%60)}s`;
const pos=(lat,lon,h=0)=>Cesium.Cartesian3.fromDegrees(lat===undefined?0:safeNum(lon),safeNum(lat),safeNum(h));
const bearing=(a,b)=>{const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl));};
let viewer=null,drone=null,homeEntity=null,targetEntity=null,routeEntity=null,last=null,lastMission=null,lastState='IDLE',timer=null,follow=false,lastCameraUpdate=0;
const MODEL='https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone.glb';
function sequence(s){const all=['s1','s2','s3','s4','s5','s6','s7','s8'];all.forEach(id=>$(id).className='step');const map={ARMING:['s1','s2'],TAKEOFF:['s1','s2','s3'],ENROUTE:['s1','s2','s3','s4'],HOVERING:['s1','s2','s3','s4','s5'],DELIVERING:['s1','s2','s3','s4','s5','s6'],RTL:['s1','s2','s3','s4','s5','s6','s7','s8'],LANDING:['s1','s2','s3','s4','s5','s6','s7','s8'],COMPLETED:all};const done=map[s]||[];done.forEach((id,i)=>$(id).className='step '+(i===done.length-1&&s!=='COMPLETED'?'active':'done'));}
function safePositions(d){const home=Array.isArray(d.home)&&d.home.length>=2?[safeNum(d.home[0]),safeNum(d.home[1])]:null;const target=Array.isArray(d.target)&&d.target.length>=2?[safeNum(d.target[0]),safeNum(d.target[1])]:null;const current=Number.isFinite(Number(d.lat))&&Number.isFinite(Number(d.lon))?[safeNum(d.lat),safeNum(d.lon)]:null;return {home,target,current};}
function apply(d){if(!viewer||!d)return;const s=String(d.state||'IDLE');const p=safePositions(d);last=d;$('source').textContent='HUB ONLINE';$('state').textContent=s;$('phase').textContent=s;$('mission').textContent=d.mission_id||'—';$('gps').textContent=p.current?`${p.current[0].toFixed(5)}, ${p.current[1].toFixed(5)}`:'—';$('speed').textContent=safeNum(d.speed_ms).toFixed(1)+' m/s';$('alt').textContent=safeNum(d.altitude_m).toFixed(1)+' m';$('vs').textContent=safeNum(d.vertical_speed_ms).toFixed(1)+' m/s';$('heading').textContent=Math.round(safeNum(d.heading_deg))+'°';$('rpm').textContent=Math.round(safeNum(d.motor_rpm));$('battery').textContent=Math.round(safeNum(d.battery_pct,100))+'%';$('dist').textContent=fmtD(d.distance_m);$('eta').textContent=fmtT(d.eta_reach_s);$('hudState').textContent=s;$('hudSpeed').textContent=safeNum(d.speed_ms).toFixed(1);$('hudAlt').textContent=safeNum(d.altitude_m).toFixed(1);$('hudVs').textContent=safeNum(d.vertical_speed_ms).toFixed(1);$('hudRpm').textContent=Math.round(safeNum(d.motor_rpm));$('hudHeading').textContent=Math.round(safeNum(d.heading_deg));$('hudBattery').textContent=Math.round(safeNum(d.battery_pct,100));$('home').textContent=p.home?`${p.home[0].toFixed(5)}, ${p.home[1].toFixed(5)}`:'—';$('target').textContent=p.target?`${p.target[0].toFixed(5)}, ${p.target[1].toFixed(5)}`:'—';sequence(s);
if(p.home){homeEntity.position=pos(p.home[0],p.home[1],0);}
if(p.target){targetEntity.position=pos(p.target[0],p.target[1],0);}
const routePts=[];if(p.home)routePts.push(pos(p.home[0],p.home[1],0));if(p.current&&s!=='IDLE')routePts.push(pos(p.current[0],p.current[1],Math.max(0,safeNum(d.altitude_m))));if(p.target)routePts.push(pos(p.target[0],p.target[1],0));if(routePts.length>=2&&routePts.every(Boolean))routeEntity.polyline.positions=routePts;
if(p.current){const h=Math.max(0,safeNum(d.altitude_m));const cp=pos(p.current[0],p.current[1],h);drone.position=cp;if(p.target){const hd=bearing(p.current,p.target);drone.orientation=Cesium.Transforms.headingPitchRollQuaternion(cp,new Cesium.HeadingPitchRoll(hd,0,0));}if(follow&&performance.now()-lastCameraUpdate>900){const cam=Cesium.Cartesian3.clone(cp);viewer.camera.flyTo({destination:Cesium.Cartesian3.add(cam,new Cesium.Cartesian3(0.008,0.008,0.004),new Cesium.Cartesian3()),duration:.55});lastCameraUpdate=performance.now();}}
if(d.mission_id&&d.mission_id!==lastMission){lastMission=d.mission_id;lastMission=d.mission_id;log('MISSION '+d.mission_id+' · distress dispatched');setStatus('Mission active · drone responding','ok');}
if(s!==lastState){lastState=s;log('STATE → '+s);} }
async function poll(){try{const r=await fetch('/drone_state',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);apply(await r.json());}catch(e){$('source').textContent='HUB OFFLINE';setStatus('Unable to read /drone_state: '+e.message,'err');}timer=setTimeout(poll,450);}
async function trigger(){const b=$('trigger');b.disabled=true;setStatus('Sending distress to hub…');try{const u='/node-alert?node=DRONE-FLIGHT-DEMO&lat=21.15786&lon=79.08939&event=1&conf=0.98&pir=1&light=30';const r=await fetch(u,{method:'GET',cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(t);log('TEST DISTRESS → '+t);setStatus('Distress accepted · mission dispatched','ok');}catch(e){log('DISTRESS ERROR → '+e.message);setStatus('Distress failed: '+e.message,'err');}finally{setTimeout(()=>b.disabled=false,900);}}
function fit(){if(!viewer||!last)return;const p=safePositions(last);const ents=[];if(homeEntity)ents.push(homeEntity);if(targetEntity&&p.target)ents.push(targetEntity);if(drone)ents.push(drone);viewer.flyTo(ents,{duration:1.25,offset:new Cesium.HeadingPitchRange(Cesium.Math.toRadians(20),Cesium.Math.toRadians(-48),Math.max(600,(last.distance_m||1200)*1.3))});}
function topdown(){if(!last||!last.lat)return;const h=Math.max(1500,(last.distance_m||1500)*1.2);viewer.camera.flyTo({destination:pos(last.lat,last.lon,h),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0},duration:1.1});}
function homeView(){const p=safePositions(last||{}).home||[21.1466,79.0889];viewer.camera.flyTo({destination:pos(p[0],p[1]+0.02,4500),orientation:{heading:Cesium.Math.toRadians(20),pitch:Cesium.Math.toRadians(-45),roll:0},duration:1.1});}
function reset(){follow=false;$('follow').textContent='FOLLOW: OFF';homeView();}
function boot(){if(!window.Cesium){setStatus('Cesium failed to load. Hard refresh and retry.','err');return;}viewer=new Cesium.Viewer('cesium',{animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,infoBox:false,selectionIndicator:false,fullscreenButton:false,shouldAnimate:false});viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors'}));viewer.scene.globe.enableLighting=true;homeEntity=viewer.entities.add({name:'SAFE HOME',position:pos(21.1466,79.0889),point:{pixelSize:13,color:Cesium.Color.CYAN,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'SAFE HOME / LAUNCH',font:'12px sans-serif',fillColor:Cesium.Color.CYAN,style:Cesium.LabelStyle.FILL_AND_OUTLINE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,pixelOffset:new Cesium.Cartesian2(0,-18)}});targetEntity=viewer.entities.add({name:'DISTRESS',position:pos(21.15786,79.08939),point:{pixelSize:14,color:Cesium.Color.RED,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DISTRESS GPS',font:'12px sans-serif',fillColor:Cesium.Color.RED,style:Cesium.LabelStyle.FILL_AND_OUTLINE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,pixelOffset:new Cesium.Cartesian2(0,-18)}});routeEntity=viewer.entities.add({name:'MISSION ROUTE',polyline:{positions:[pos(21.1466,79.0889,0),pos(21.15786,79.08939,0)],width:4,material:Cesium.Color.CYAN.withAlpha(.8),clampToGround:true}});drone=viewer.entities.add({name:'VanniKawachh Drone',position:pos(21.1466,79.0889,0),model:{uri:MODEL,scale:1.65,minimumPixelSize:70,maximumScale:2200},label:{text:'VANNIKAWACHH UAV',font:'12px sans-serif',fillColor:Cesium.Color.WHITE,style:Cesium.LabelStyle.FILL_AND_OUTLINE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-32)}});setStatus('3D globe ready · Hub connected','ok');log('Cesium viewer ready');viewer.camera.flyTo({destination:pos(21.150,79.079,6500),orientation:{heading:Cesium.Math.toRadians(10),pitch:Cesium.Math.toRadians(-48),roll:0},duration:1.3});poll();}
$('trigger').onclick=trigger;$('live').onclick=()=>poll();$('fit').onclick=fit;$('topdown').onclick=topdown;$('homeView').onclick=homeView;$('follow').onclick=()=>{follow=!follow;$('follow').textContent=follow?'FOLLOW: ON':'FOLLOW: OFF';setStatus(follow?'Soft-follow enabled':'Free camera enabled','ok');};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
</script></body></html>'''
