"""Reliable geographic 3D flight viewer for VanniKawachh.

The browser reads one source of truth: /drone_state. It does not invent a second
mission timeline. The aircraft altitude, GPS, speed and state therefore match the
same Wokwi -> hub mission visible elsewhere.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Geographic Drone Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Widgets/widgets.css">
<style>
:root{--bg:#060d13;--panel:#09161f;--line:#294452;--txt:#edf7fa;--muted:#8ea6b4;--green:#34e2b3;--amber:#ffb34c;--red:#ff6875;--blue:#68b5ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 430px;width:100vw;height:100vh}#world{position:relative;min-width:0;min-height:0}.top{position:absolute;z-index:10;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;pointer-events:none}.pill{background:#07131eea;border:1px solid var(--line);border-radius:999px;padding:8px 12px;backdrop-filter:blur(8px)}.pill b{color:#fff}.live{color:var(--green)}#cesium{position:absolute;inset:0}.badge{position:absolute;left:13px;bottom:13px;z-index:11;background:#07131eea;border:1px solid var(--line);border-radius:8px;padding:7px 10px;font-size:10px}.badge b{color:var(--green)}
#side{overflow:auto;background:#07121bf8;border-left:1px solid var(--line);padding:13px}.title{font-size:21px;font-weight:900}.sub,.note{font-size:10px;color:var(--muted);line-height:1.5}.card{background:linear-gradient(180deg,#0e1f2a,#09151d);border:1px solid var(--line);border-radius:12px;padding:11px;margin:9px 0}.lab{font-size:10px;color:var(--muted);letter-spacing:.1em;font-weight:900}.big{font-size:28px;font-weight:900;margin:2px 0}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.val{font-weight:800;text-align:right}
.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;color:#677f8c;background:#09151d}.step.active{border-color:#916729;background:#211a10;color:#ffdfa0;font-weight:800}.step.done{border-color:#286b5a;background:#0c211b;color:#aef4e1}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#3a4e57;margin-right:7px}.step.active .dot{background:var(--amber)}.step.done .dot{background:var(--green)}
.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:3px;align-items:center}.node{padding:7px 3px;text-align:center;font-size:8px;border:1px solid #294553;border-radius:7px;background:#0a1922}.node.active{border-color:var(--green);box-shadow:0 0 12px #34e2b322}.arr{color:var(--green)}
.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);border-radius:8px;padding:10px;background:#122432;color:#fff;font-weight:900;cursor:pointer}.btn.primary{background:#0d2c24;border-color:#286b5a}.btn.warnBtn{background:#291d10;border-color:#6f4f24}.btn:disabled{opacity:.45;cursor:wait}.btn:hover:not(:disabled){filter:brightness(1.1)}
.status{padding:8px 10px;border-radius:8px;border:1px solid #1c3744;background:#061016;font-size:10px;min-height:18px}.status.ok{border-color:#286b5a;color:#aef4e1}.status.err{border-color:#8f3543;color:#ffb8c0}.status.busy{border-color:#916729;color:#ffdfa0}#log{height:82px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb9c7}
@media(max-width:900px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:30;right:0;top:0;bottom:0;width:min(430px,95vw);box-shadow:-20px 0 50px #000c}}
</style></head><body>
<div id="app"><section id="world"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · GEOGRAPHIC DRONE FLIGHT</div><div class="pill"><span class="live">●</span> <b id="source">CHECKING…</b></div></div><div id="cesium"></div><div class="badge">WORLD: <b id="worldState">LOADING</b></div></section>
<aside id="side"><div class="title">Autonomous Mission Flight</div><div class="sub">This page is the geographic flight layer. It uses the live <b>/drone_state</b> position/state produced by the Wokwi → hub dispatch chain. A separate SITL bridge can feed the same endpoint with real ArduPilot telemetry.</div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude AGL</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Distance</span><span id="dist" class="val">—</span></div><div class="row"><span>ETA to target</span><span id="eta" class="val">—</span></div><div class="row"><span>Physics source</span><span id="physics" class="val">Browser mission sim</span></div></div>
<div class="card"><div class="lab">FLIGHT SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger</div><div class="step" id="s2"><span class="dot"></span>Arm + rotor spool</div><div class="step" id="s3"><span class="dot"></span>Vertical takeoff</div><div class="step" id="s4"><span class="dot"></span>Cruise to distress GPS</div><div class="step" id="s5"><span class="dot"></span>Hover at target</div><div class="step" id="s6"><span class="dot"></span>Payload bay opens</div><div class="step" id="s7"><span class="dot"></span>Health kit release</div><div class="step" id="s8"><span class="dot"></span>RTL + landing</div></div></div>
<div class="card"><div class="lab">AIRCRAFT SYSTEMS</div><div class="row"><span>Motors / props</span><span id="motors" class="val ok">OFF</span></div><div class="row"><span>Flight controller</span><span class="val ok">PIXHAWK / ARDUPILOT</span></div><div class="row"><span>GPS / compass</span><span class="val ok">INPUT</span></div><div class="row"><span>Companion / LoRa</span><span id="link" class="val">STANDBY</span></div><div class="row"><span>Payload servo</span><span id="servo" class="val">CLOSED</span></div><div class="row"><span>Health kit</span><span id="kit" class="val">SECURED</span></div></div>
<div class="card"><div class="lab">CONTROL SIGNAL</div><div class="chain"><div id="n1" class="node">ESP32<br>SENSOR</div><div class="arr">→</div><div id="n2" class="node">HUB<br>DISPATCH</div><div class="arr">→</div><div id="n3" class="node">PIXHAWK<br>ARDUPILOT</div><div class="arr">→</div><div id="n4" class="node">ESCs<br>+ SERVO</div></div></div>
<div class="buttons"><button id="live" class="btn primary">LIVE HUB</button><button id="trigger" class="btn">TEST DISTRESS</button><button id="fit" class="btn">FIT MISSION</button><button id="reset" class="btn warnBtn">RESET VIEW</button></div><div id="status" class="status">Initializing…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div><div class="note">For actual aerodynamic validation use the repository's ArduPilot SITL + Gazebo integration. Render hosts this geographic visualisation and mission API; the browser page does not pretend to be the physics engine.</div></aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Cesium.js"></script>
<script>
(function(){
const $=id=>document.getElementById(id), log=m=>{const e=$("log");e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight}, distFmt=m=>m==null?'—':m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`,timeFmt=s=>s==null?'—':s>=3600?`${Math.floor(s/3600)}h ${Math.floor((s%3600)/60)}m`:s>=60?`${Math.floor(s/60)}m ${Math.round(s)%60}s`:`${Math.round(s)}s`;
let viewer=null,aircraft=null,trail=[],home=null,target=null,lastState="IDLE",lastMission=null,timer=null,live=true,last=null,hasFit=false;
function status(t,k){const e=$("status");e.textContent=t;e.className="status"+(k?" "+k:"")}
function cart(lat,lon,h){return Cesium.Cartesian3.fromDegrees(Number(lon),Number(lat),Number(h||0))}
function bearing(a,b){const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))}
function setChecklist(s){const done={s1:["ARMING","TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s2:["TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s3:["ENROUTE","HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s4:["ENROUTE","HOVERING","DELIVERING","RTL","LANDING"],s5:["HOVERING","DELIVERING","RTL","LANDING","COMPLETED"],s6:["DELIVERING","RTL","LANDING","COMPLETED"],s7:["RTL","LANDING","COMPLETED"],s8:["RTL","LANDING","COMPLETED"]};Object.entries(done).forEach(([id,a])=>$(id).className="step"+(a.includes(s)?" done":""));const active={ARMING:"s2",TAKEOFF:"s3",ENROUTE:"s4",HOVERING:"s5",DELIVERING:"s6",RTL:"s8",LANDING:"s8"}[s];if(active)$(active).className="step active"}
function setState(d){last=d;const s=d.state||"IDLE";$("state").textContent=s;$("state").className="big "+(s==="FAILED"?"bad":(["TAKEOFF","ENROUTE","RTL","LANDING"].includes(s)?"warn":"ok"));$("mission").textContent=d.mission_id||"—";$("gps").textContent=d.lat!=null?`${Number(d.lat).toFixed(5)}, ${Number(d.lon).toFixed(5)}`:"—";$("speed").textContent=`${Number(d.speed_ms||d.ground_speed_ms||0).toFixed(1)} m/s`;$("alt").textContent=`${Number(d.altitude_m||0).toFixed(1)} m`;$("dist").textContent=distFmt(d.distance_m);$("eta").textContent=timeFmt(d.eta_reach_s);$("physics").textContent=d.source==="phone"?"ArduPilot/SITL bridge":"Browser mission sim";const armed=["TAKEOFF","ENROUTE","HOVERING","DELIVERING","RTL","LANDING"].includes(s);$("motors").textContent=armed?"RUNNING":"OFF";$("link").textContent=s==="IDLE"?"STANDBY":"ACTIVE";$("servo").textContent=s==="DELIVERING"?"OPEN":"CLOSED";$("kit").textContent=d.kit_dropped?"DROPPED":"SECURED";["n1","n2","n3","n4"].forEach(id=>$(id).classList.remove("active"));if(s!=="IDLE")$("n1").classList.add("active");if(s!=="IDLE")$("n2").classList.add("active");if(armed)$("n3").classList.add("active");if(["DELIVERING","RTL","LANDING","COMPLETED"].includes(s))$("n4").classList.add("active");setChecklist(s);if(s!==lastState){log(`STATE → ${s}`);lastState=s}if(d.mission_id&&d.mission_id!==lastMission){lastMission=d.mission_id;log(`MISSION ${d.mission_id}`)}if(d.lat!=null){trail.push(cart(d.lat,d.lon,d.altitude_m||0));if(trail.length>700)trail.shift();if(aircraft){aircraft.position=cart(d.lat,d.lon,d.altitude_m||0);aircraft.orientation=Cesium.Transforms.headingPitchRollQuaternion(aircraft.position,new Cesium.HeadingPitchRoll(d.heading_deg==null?bearing([d.lat,d.lon],d.target||[d.lat,d.lon]):Cesium.Math.toRadians(d.heading_deg),0,0))}if(home==null&&d.home){home=cart(d.home[0],d.home[1],0);viewer.entities.add({position:home,ellipse:{semiMajorAxis:18,semiMinorAxis:18,material:Cesium.Color.CYAN.withAlpha(.15),outline:true,outlineColor:Cesium.Color.CYAN}})}if(d.target){target=cart(d.target[0],d.target[1],0);if(!$("targetMarker")){ }}}}
async function init(){viewer=new Cesium.Viewer("cesium",{imageryProvider:new Cesium.UrlTemplateImageryProvider({url:"https://tile.openstreetmap.org/{z}/{x}/{y}.png",credit:"© OpenStreetMap contributors"}),terrainProvider:new Cesium.EllipsoidTerrainProvider(),baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,animation:false,timeline:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false});viewer.scene.globe.enableLighting=true;viewer.scene.fog.enabled=true;$("worldState").textContent="OSM surface";status("World loaded — waiting for mission","ok");try{const b=await Cesium.createOsmBuildingsAsync();viewer.scene.primitives.add(b);$("worldState").textContent="OSM + 3D buildings"}catch(e){log("3D buildings unavailable; keeping map surface")}
aircraft=viewer.entities.add({name:"VanniKawachh Response Drone",position:cart(21.1466,79.0889,0),model:{uri:"https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone_nologo.glb",minimumPixelSize:90,maximumScale:250,runAnimations:true,shadows:Cesium.ShadowMode.ENABLED},path:{show:true,width:4,resolution:2,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.12,color:Cesium.Color.CYAN})}});aircraft.position=new Cesium.ConstantPositionProperty(cart(21.1466,79.0889,0));window.flightViewer=viewer;$("fit").onclick=fitMission;$("reset").onclick=resetView;status("Ready","ok");poll()}
function fitMission(){if(!viewer||!last){status("No mission yet — trigger a distress first","busy");return}const pts=[];if(last.home)pts.push(cart(last.home[0],last.home[1],0));if(last.target)pts.push(cart(last.target[0],last.target[1],20));if(last.lat!=null)pts.push(cart(last.lat,last.lon,last.altitude_m||0));if(pts.length)viewer.camera.flyTo({destination:Cesium.Rectangle.fromCartesianArray(pts),duration:1.4});status("Fitting launch → live aircraft → target","ok")}
function resetView(){if(viewer)viewer.camera.setView({destination:cart(last?.home?.[0]||21.1466,last?.home?.[1]||79.0889,4500)});status("View reset to launch area","ok")}
async function readHub(){try{const r=await fetch("/drone_state?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);setState(await r.json());$("source").textContent="LIVE HUB";status("Connected to /drone_state","ok");return true}catch(e){$("source").textContent="HUB ERROR";status(`Hub error: ${e.message}`,"err");return false}}
function poll(){if(!live)return;readHub().finally(()=>timer=setTimeout(poll,600))}
$("live").onclick=async()=>{live=true;status("Connecting to deployed hub…","busy");const ok=await readHub();log(ok?"LIVE HUB → connected":"LIVE HUB → connection failed");poll()};
$("trigger").onclick=async()=>{const b=$("trigger");b.disabled=true;status("Sending TEST DISTRESS…","busy");try{const r=await fetch(`/node-alert?node=WEB-FLIGHT&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30`,{method:"GET",cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${text}`);log("DISTRESS → "+text);status("Distress accepted — mission starting","ok");live=true;poll()}catch(e){status(`Trigger failed: ${e.message}`,"err");log("TRIGGER ERROR → "+e.message)}finally{setTimeout(()=>b.disabled=false,700)}};
init().catch(e=>{status(`Viewer failed: ${e.message}`,"err");log("INIT ERROR → "+e.message)});
})();
</script></body></html>'''
