"""Geographic 3D drone flight simulation page for VanniKawachh."""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VanniKawachh Drone Flight</title>
<link href="https://cdn.jsdelivr.net/npm/cesium@latest/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
<style>
:root{--bg:#071018;--p:#09151e;--line:#29404e;--txt:#e9f5f8;--mut:#8ea7b5;--g:#32e0b0;--a:#ffb24a;--r:#ff6875;--b:#67b0ff}*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Inter,Segoe UI,Arial}.app{display:grid;grid-template-columns:minmax(0,1fr) 430px;height:100vh}.map{position:relative}.top{position:absolute;z-index:10;left:12px;right:12px;top:12px;display:flex;justify-content:space-between}.pill{background:#07141ee8;border:1px solid var(--line);padding:8px 12px;border-radius:20px}.live{color:var(--g)}.side{overflow:auto;background:#08131bf7;border-left:1px solid var(--line);padding:13px}.title{font-size:20px;font-weight:900}.sub,.note{color:var(--mut);font-size:10px;line-height:1.45}.card{background:linear-gradient(180deg,#0e1e29,#09151d);border:1px solid var(--line);border-radius:11px;padding:11px;margin:9px 0}.lab{font-size:10px;color:var(--mut);font-weight:800;letter-spacing:.1em}.big{font-size:26px;font-weight:900;margin:3px 0}.row{display:flex;justify-content:space-between;margin:7px 0}.val{font-weight:800}.ok{color:var(--g)}.warn{color:var(--a)}.bad{color:var(--r)}.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;background:#09151d;color:#637987}.step.active{border-color:#8b6224;background:#211a0f;color:#ffdca3;font-weight:800}.step.done{border-color:#286c5a;background:#0b211b;color:#adf3e0}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#364a54;margin-right:7px}.step.active .dot{background:var(--a)}.step.done .dot{background:var(--g)}.btns{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);background:#112432;color:white;padding:10px;border-radius:8px;font-weight:800;cursor:pointer}.primary{background:#0e2b24;border-color:#286f5d}.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;align-items:center;gap:3px}.node{font-size:8px;text-align:center;padding:7px 2px;border:1px solid #284354;border-radius:7px}.node.active{border-color:var(--g);box-shadow:0 0 12px #32e0b02e}.arr{color:var(--g)}svg{width:100%;height:160px;background:#08131b;border:1px solid #223b49;border-radius:9px}.t{fill:#bdd1d9;font-size:9px;font-weight:800}.wire{stroke:#4d6b78;stroke-width:2}.arm{stroke:#536e79;stroke-width:7;stroke-linecap:round}.m{fill:#182933;stroke:#678491}.fc{fill:#173b47;stroke:#32e0b0}.bat{fill:#3c2d17;stroke:#ffb24a}.gps{fill:#113027;stroke:#32e0b0}.comp{fill:#172b3b;stroke:#67b0ff}.pay{fill:#302415;stroke:#ffb24a}.cam{fill:#182832;stroke:#67b0ff}#log{height:90px;overflow:auto;background:#061018;border:1px solid #19303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb8c7}@media(max-width:900px){.app{grid-template-columns:1fr}.side{position:absolute;z-index:20;right:0;top:0;bottom:0;width:min(430px,95vw);box-shadow:-20px 0 40px #000b}}
</style></head><body><div class="app"><section class="map"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · AUTONOMOUS DRONE RESPONSE</div><div class="pill"><span class="live">●</span> <b id="src">LIVE HUB</b></div></div><div id="cesium" style="width:100%;height:100%"></div></section>
<aside class="side"><div class="title">Drone Flight Simulator</div><div class="sub">Real geographic 3D globe + live route. The aircraft, camera, mission checklist and hardware indicators all consume the deployed <b>/drone_state</b> feed.</div>
<div class="card"><div class="lab">FLIGHT STATE</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span class="val" id="mission">—</span></div><div class="row"><span>Distance</span><span class="val" id="dist">—</span></div><div class="row"><span>Real ETA</span><span class="val" id="eta">—</span></div><div class="row"><span>Playback</span><span class="val">accelerated presentation</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger received</div><div class="step" id="s2"><span class="dot"></span>Arm / spin four rotors</div><div class="step" id="s3"><span class="dot"></span>Takeoff</div><div class="step" id="s4"><span class="dot"></span>Navigate to distress GPS</div><div class="step" id="s5"><span class="dot"></span>Hover at incident</div><div class="step" id="s6"><span class="dot"></span>Open payload servo</div><div class="step" id="s7"><span class="dot"></span>Drop health kit</div><div class="step" id="s8"><span class="dot"></span>RTL / land</div></div></div>
<div class="card"><div class="lab">LIVE AIRCRAFT</div><div class="row"><span>4 × BLDC / ESC</span><span class="val ok" id="motors">OFF</span></div><div class="row"><span>Flight controller</span><span class="val ok">CONNECTED</span></div><div class="row"><span>GPS / compass</span><span class="val ok">LOCKED</span></div><div class="row"><span>Companion / LoRa</span><span class="val ok">ONLINE</span></div><div class="row"><span>Camera</span><span class="val ok" id="cam">STANDBY</span></div><div class="row"><span>Payload servo</span><span class="val" id="servo">CLOSED</span></div><div class="row"><span>Health kit</span><span class="val" id="kit">SECURED</span></div></div>
<div class="card"><div class="lab">ON-BOARD HARDWARE / CIRCUIT</div><svg viewBox="0 0 400 160"><line class="arm" x1="150" y1="70" x2="55" y2="30"/><line class="arm" x1="250" y1="70" x2="345" y2="30"/><line class="arm" x1="150" y1="88" x2="55" y2="132"/><line class="arm" x1="250" y1="88" x2="345" y2="132"/><circle class="m" cx="55" cy="30" r="16"/><circle class="m" cx="345" cy="30" r="16"/><circle class="m" cx="55" cy="132" r="16"/><circle class="m" cx="345" cy="132" r="16"/><rect class="fc" x="165" y="53" width="70" height="52" rx="8"/><text class="t" x="178" y="77">FLIGHT</text><text class="t" x="175" y="91">CONTROLLER</text><rect class="gps" x="178" y="4" width="44" height="17" rx="4"/><text class="t" x="187" y="16">GPS</text><rect class="bat" x="173" y="115" width="55" height="22" rx="5"/><text class="t" x="188" y="130">LiPo</text><rect class="comp" x="277" y="103" width="72" height="24" rx="5"/><text class="t" x="286" y="118">COMP / LoRa</text><rect class="cam" x="160" y="17" width="29" height="18" rx="4"/><text class="t" x="196" y="30">CAM</text><rect class="pay" x="210" y="138" width="78" height="18" rx="4"/><text class="t" x="223" y="151">SERVO + KIT</text><path class="wire" fill="none" d="M180 21 L190 53 M222 21 L214 53 M165 72 L55 30 M235 72 L345 30 M165 92 L55 132 M235 92 L345 132 M200 105 L200 115 M226 136 L245 138 M235 90 L277 112"/><text class="t" x="18" y="16">M1</text><text class="t" x="354" y="16">M2</text><text class="t" x="18" y="151">M3</text><text class="t" x="354" y="151">M4</text></svg><div class="note">LiPo powers the distribution/ESC chain. GPS/compass feeds the flight controller. Companion/LoRa carries mission communication. Servo releases the first-aid payload. Camera provides visual verification.</div></div>
<div class="card"><div class="lab">CONTROL SIGNAL</div><div class="chain"><div class="node" id="n1">ESP32<br>SENSOR</div><div class="arr">→</div><div class="node" id="n2">HUB<br>DISPATCH</div><div class="arr">→</div><div class="node" id="n3">FLIGHT<br>CONTROLLER</div><div class="arr">→</div><div class="node" id="n4">ESCs /<br>SERVO</div></div></div>
<div class="btns"><button class="btn primary" id="live">LIVE HUB</button><button class="btn" id="trigger">TRIGGER TEST</button><button class="btn" id="fit">FIT ROUTE</button><button class="btn" id="reset">RESET</button></div><div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div><div class="note">This is the geographic presentation layer. The existing SimDrone supplies the live mission/GPS state; ArduPilot SITL remains the separate flight-physics validation layer.</div></aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@latest/Build/Cesium/Cesium.js"></script><script>
const $=id=>document.getElementById(id), log=m=>{const e=$('log');e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};let viewer,drone,home,target,route,live=true,lastM=null,lastS='IDLE',lastD=null;
const model='https://cdn.jsdelivr.net/gh/CesiumGS/cesium@main/Apps/SampleData/models/CesiumDrone/CesiumDrone.glb';
const C=(lat,lon,h=0)=>Cesium.Cartesian3.fromDegrees(+lon,+lat,h), fM=m=>m==null?'—':m<1000?Math.round(m)+' m':(m/1000).toFixed(2)+' km', fS=s=>s==null?'—':s>=3600?Math.floor(s/3600)+'h '+Math.floor((s%3600)/60)+'m':s>=60?Math.floor(s/60)+'m '+(s%60)+'s':Math.round(s)+'s';
function heading(a,b){if(!a||!b)return 0;const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))}
function applyHardware(s,d){const fly=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL'].includes(s);$('motors').textContent=fly?'SPINNING':'OFF';$('motors').className='val '+(fly?'warn':'ok');$('cam').textContent=fly?'ACTIVE':'STANDBY';$('servo').textContent=s==='DELIVERING'?'OPEN':'CLOSED';$('kit').textContent=d&&d.kit_dropped?'DROPPED':'SECURED';['n1','n2','n3','n4'].forEach(id=>$(id).classList.remove('active'));if(s!=='IDLE')$('n1').classList.add('active');if(s!=='IDLE')$('n2').classList.add('active');if(fly)$('n3').classList.add('active');if(['DELIVERING','RTL','COMPLETED'].includes(s))$('n4').classList.add('active')}
function steps(s){const all=['s1','s2','s3','s4','s5','s6','s7','s8'];all.forEach(id=>$(id).className='step');const done={s1:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s4:['HOVERING','DELIVERING','RTL','COMPLETED'],s5:['DELIVERING','RTL','COMPLETED'],s6:['RTL','COMPLETED'],s7:['RTL','COMPLETED'],s8:['COMPLETED']};for(const [id,ss] of Object.entries(done))if(ss.includes(s))$(id).className='step done';const active={TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8'}[s];if(active)$(active).className='step active';if(s==='DELIVERING')$('s7').className='step active';if(s==='COMPLETED')all.forEach(id=>$(id).className='step done')}
function setCameraToMission(){if(route)viewer.flyTo(route,{duration:1.3,offset:new Cesium.HeadingPitchRange(0,Cesium.Math.toRadians(-35),15000)})}
function apply(d){lastD=d;if(!d)return;const s=d.state||'IDLE';$('state').textContent=s;$('state').className='big '+(['TAKEOFF','ENROUTE','RTL'].includes(s)?'warn':s==='FAILED'?'bad':'ok');$('mission').textContent=d.mission_id||'—';$('dist').textContent=fM(d.distance_m);$('eta').textContent=fS(d.eta_reach_s);applyHardware(s,d);steps(s);if(d.home){home.position=C(d.home[0],d.home[1]);if(!home.label)home.label={text:'DRONE BASE'}}if(d.target){target.position=C(d.target[0],d.target[1]);route.polyline.positions=[C(d.home?.[0]||d.lat,d.home?.[1]||d.lon),C(d.target[0],d.target[1])];if(!lastM){setCameraToMission()}}if(d.lat!=null){const alt=['ENROUTE','HOVERING','DELIVERING','RTL'].includes(s)?15:s==='TAKEOFF'?5:0;drone.position=C(d.lat,d.lon,alt);if(d.target)drone.orientation=Cesium.Transforms.headingPitchRollQuaternion(drone.position,new Cesium.HeadingPitchRoll(heading([d.lat,d.lon],d.target),0,0))}if(d.mission_id&&d.mission_id!==lastM){lastM=d.mission_id;log('MISSION '+d.mission_id);viewer.trackedEntity=drone;setTimeout(setCameraToMission,300)}if(s!==lastS){log('STATE → '+s);lastS=s;if(['ENROUTE','HOVERING','DELIVERING','RTL'].includes(s))viewer.trackedEntity=drone;if(s==='COMPLETED')viewer.trackedEntity=undefined}}
async function poll(){if(!live)return;try{const r=await fetch('/drone_state',{cache:'no-store'});if(r.ok){$('src').textContent='LIVE HUB';apply(await r.json())}}catch(e){$('src').textContent='HUB OFFLINE'}setTimeout(poll,250)}
async function init(){viewer=new Cesium.Viewer('cesium',{animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,infoBox:false,selectionIndicator:false,fullscreenButton:false});viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',maximumLevel:19,credit:'© OpenStreetMap'}));viewer.scene.globe.enableLighting=true;viewer.scene.screenSpaceCameraController.enableCollisionDetection=false;drone=viewer.entities.add({name:'VanniKawachh Drone',position:C(21.1188,79.0195),model:{uri:model,scale:1.6,minimumPixelSize:90,maximumScale:5000}});home=viewer.entities.add({name:'Drone Base',position:C(21.1188,79.0195),point:{pixelSize:12,color:Cesium.Color.CYAN,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DRONE BASE',font:'12px sans-serif',fillColor:Cesium.Color.CYAN,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-15)}});target=viewer.entities.add({name:'Distress Target',position:C(21.1466,79.0889),point:{pixelSize:13,color:Cesium.Color.RED,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DISTRESS',font:'12px sans-serif',fillColor:Cesium.Color.RED,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-15)}});route=viewer.entities.add({name:'Mission Route',polyline:{positions:[C(21.1188,79.0195),C(21.1466,79.0889)],width:5,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.15,color:Cesium.Color.CYAN}),clampToGround:false}});log('3D map ready · waiting for Wokwi/hub mission');poll()}
$('live').onclick=()=>{live=true;log('LIVE HUB');poll()};$('fit').onclick=()=>setCameraToMission();$('reset').onclick=()=>{viewer.trackedEntity=undefined;viewer.camera.flyTo({destination:C(79.0889,21.1466,25000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-55),roll:0},duration:1});log('Camera reset')};$('trigger').onclick=async()=>{try{const r=await fetch('/node-alert?node=DRONE-SIM&lat=21.1466&lon=79.0889&event=1&conf=0.99&pir=1&light=30',{method:'POST'});const j=await r.json();log(j.dispatched?'DISPATCHED '+j.mission_id:JSON.stringify(j));live=true;poll()}catch(e){log('Trigger failed: '+e.message)}};init();
</script></body></html>'''
