"""Parse-safe geographic flight viewer for VanniKawachh."""
from fastapi.responses import HTMLResponse

def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML

HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Drone Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Widgets/widgets.css">
<style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#061018;color:#edf7fa;font:12px Segoe UI,Arial}#app{display:grid;grid-template-columns:minmax(0,1fr) 390px;height:100vh}#world{position:relative}#cesium{position:absolute;inset:0}.top{position:absolute;z-index:5;left:12px;right:12px;top:12px;display:flex;justify-content:space-between}.pill,.help{background:#07131eee;border:1px solid #284452;border-radius:10px;padding:8px 11px}.help{position:absolute;z-index:4;left:12px;bottom:12px;color:#9bb0bc}.live{color:#35e2b3}.side{overflow:auto;background:#07121bf8;border-left:1px solid #284452;padding:13px}.title{font-size:20px;font-weight:900}.sub,.note{color:#91a7b3;font-size:10px;line-height:1.5}.card{border:1px solid #284452;border-radius:10px;background:#0b1a24;padding:10px;margin:9px 0}.lab{font-size:9px;letter-spacing:.1em;color:#91a7b3;font-weight:900}.big{font-size:26px;font-weight:900;margin:3px 0}.ok{color:#35e2b3}.warn{color:#ffb34c}.row{display:flex;justify-content:space-between;margin:6px 0}.val{font-weight:800}.seq{display:grid;gap:4px}.step{padding:6px 8px;border:1px solid #1d3440;border-radius:7px;color:#6d828d}.step.done{background:#0c211b;color:#b0f5e3;border-color:#2b6b5a}.step.active{background:#211a10;color:#ffe0a0;border-color:#8f6527}.btns{display:grid;grid-template-columns:1fr 1fr;gap:6px}.btn{padding:9px;border-radius:8px;border:1px solid #284452;background:#122431;color:#fff;font-weight:800;cursor:pointer}.btn.primary{background:#0d2d25;border-color:#286b5a}.status{margin-top:8px;padding:8px;border:1px solid #284452;border-radius:8px;min-height:16px}.err{border-color:#913443;color:#ffbac1}.okbox{border-color:#286b5a;color:#b0f5e3}.log{height:80px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px monospace}
</style></head><body><div id="app"><section id="world"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · GEOGRAPHIC FLIGHT</div><div class="pill"><span class="live">●</span> <b id="src">CHECKING</b></div></div><div id="cesium"></div><div class="help">Left-drag orbit · Right-drag pan · Wheel zoom</div></section><aside class="side"><div class="title">Autonomous Mission Flight</div><div class="sub">Same deployed /drone_state source as Wokwi → hub. The map camera is free unless FOLLOW is enabled.</div><div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Motor RPM</span><span id="rpm" class="val">0</span></div><div class="row"><span>Distance</span><span id="dist" class="val">—</span></div><div class="row"><span>ETA</span><span id="eta" class="val">—</span></div></div><div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div id="s1" class="step">Distress trigger</div><div id="s2" class="step">Arm / rotor spool</div><div id="s3" class="step">Vertical takeoff</div><div id="s4" class="step">Cruise to target</div><div id="s5" class="step">Hover at target</div><div id="s6" class="step">Open payload</div><div id="s7" class="step">Drop health kit</div><div id="s8" class="step">RTL / landing</div></div></div><div class="card"><div class="lab">SYSTEM</div><div class="row"><span>Motors</span><span id="motors" class="val ok">OFF</span></div><div class="row"><span>Pixhawk / ArduPilot</span><span class="val ok">CONNECTED</span></div><div class="row"><span>Companion / LoRa</span><span id="link" class="val">STANDBY</span></div><div class="row"><span>Servo</span><span id="servo" class="val">CLOSED</span></div><div class="row"><span>Kit</span><span id="kit" class="val">SECURED</span></div></div><div class="btns"><button id="live" class="btn primary">LIVE HUB</button><button id="trigger" class="btn">TEST DISTRESS</button><button id="fit" class="btn">FIT ROUTE</button><button id="follow" class="btn">FOLLOW: OFF</button><button id="top" class="btn">TOP DOWN</button><button id="reset" class="btn">RESET VIEW</button></div><div id="status" class="status">Starting viewer…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log" class="log"></div></div><div class="note">This is the geographic visualization layer. ArduPilot SITL + Gazebo remains the true physics validation layer.</div></aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Cesium.js"></script>
<script>
(function(){
var $=function(id){return document.getElementById(id)},viewer,aircraft,home,target,route,last=null,follow=false,timer=null,lastState='IDLE',lastMission=null;
function write(m){var e=$('log');e.innerHTML+='<div>'+new Date().toLocaleTimeString()+' · '+m+'</div>';e.scrollTop=e.scrollHeight}
function status(m,c){var e=$('status');e.textContent=m;e.className='status '+(c||'')}
function pos(lat,lon,h){return Cesium.Cartesian3.fromDegrees(Number(lon),Number(lat),Number(h||0))}
function dist(m){if(m==null)return '—';return m<1000?Math.round(m)+' m':(m/1000).toFixed(2)+' km'}
function tm(s){if(s==null)return '—';if(s<60)return Math.round(s)+'s';return Math.floor(s/60)+'m '+(Math.round(s)%60)+'s'}
function bearing(a,b){var p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))}
function sequence(s){var done={s1:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s4:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s5:['HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s6:['DELIVERING','RTL','LANDING','COMPLETED'],s7:['RTL','LANDING','COMPLETED'],s8:['RTL','LANDING','COMPLETED']};Object.keys(done).forEach(function(id){$(id).className='step '+(done[id].indexOf(s)>=0?'done':'')});var active={ARMING:'s2',TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8',LANDING:'s8'}[s];if(active)$(active).className='step active'}
function apply(d){last=d;var s=d.state||'IDLE';$('state').textContent=s;$('state').className='big '+(['TAKEOFF','ENROUTE','RTL','LANDING'].indexOf(s)>=0?'warn':'ok');$('mission').textContent=d.mission_id||'—';$('gps').textContent=d.lat!=null?Number(d.lat).toFixed(5)+', '+Number(d.lon).toFixed(5):'—';$('speed').textContent=Number(d.speed_ms||0).toFixed(1)+' m/s';$('alt').textContent=Number(d.altitude_m||0).toFixed(1)+' m';$('rpm').textContent=Math.round(Number(d.motor_rpm||0));$('dist').textContent=dist(d.distance_m);$('eta').textContent=tm(d.eta_reach_s);var armed=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].indexOf(s)>=0;$('motors').textContent=armed?'RUNNING':'OFF';$('link').textContent=s==='IDLE'?'STANDBY':'ACTIVE';$('servo').textContent=s==='DELIVERING'?'OPEN':'CLOSED';$('kit').textContent=d.kit_dropped?'DROPPED':'SECURED';sequence(s);if(s!==lastState){write('STATE → '+s);lastState=s}if(d.mission_id&&d.mission_id!==lastMission){write('MISSION '+d.mission_id);lastMission=d.mission_id}if(d.lat!=null){aircraft.position=pos(d.lat,d.lon,d.altitude_m);aircraft.orientation=Cesium.Transforms.headingPitchRollQuaternion(aircraft.position,new Cesium.HeadingPitchRoll(d.heading_deg==null?(d.target?bearing([d.lat,d.lon],d.target):0):Cesium.Math.toRadians(d.heading_deg),0,0));if(home==null&&d.home){home=pos(d.home[0],d.home[1],0);viewer.entities.add({position:home,point:{pixelSize:12,color:Cesium.Color.CYAN},label:{text:'SAFE LANDING / HOME',font:'11px sans-serif',pixelOffset:new Cesium.Cartesian2(0,-18)}})}if(target==null&&d.target){target=pos(d.target[0],d.target[1],0);viewer.entities.add({position:target,point:{pixelSize:14,color:Cesium.Color.RED},label:{text:'DISTRESS',font:'11px sans-serif',fillColor:Cesium.Color.RED,pixelOffset:new Cesium.Cartesian2(0,-18)}});if(!route&&home){route=viewer.entities.add({polyline:{positions:[home,target],width:4,material:Cesium.Color.CYAN}})}}if(follow)viewer.trackedEntity=aircraft}}
function fit(){if(!last){status('Trigger a distress first','');return}var arr=[];if(last.home)arr.push(pos(last.home[0],last.home[1],0));if(last.target)arr.push(pos(last.target[0],last.target[1],15));if(last.lat!=null)arr.push(pos(last.lat,last.lon,last.altitude_m));if(arr.length)viewer.camera.flyTo({destination:Cesium.Rectangle.fromCartesianArray(arr),duration:1.2});status('Fitted home → aircraft → target','okbox')}
function poll(){fetch('/drone_state?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(function(d){$('src').textContent='LIVE HUB';status('Connected to /drone_state','okbox');apply(d)}).catch(function(e){$('src').textContent='HUB ERROR';status('Hub error: '+e.message,'err')}).finally(function(){timer=setTimeout(poll,700)})}
function init(){viewer=new Cesium.Viewer('cesium',{imageryProvider:new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors'}),terrainProvider:new Cesium.EllipsoidTerrainProvider(),baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,animation:false,timeline:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false});viewer.scene.globe.enableLighting=true;aircraft=viewer.entities.add({name:'VanniKawachh Drone',position:pos(21.1466,79.0889,0),model:{uri:'https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone_nologo.glb',minimumPixelSize:80,maximumScale:250}});status('Viewer ready — drag to orbit, wheel to zoom','okbox');poll()}
$('live').onclick=function(){status('Connecting…','');poll()};$('trigger').onclick=function(){var b=$('trigger');b.disabled=true;status('Sending TEST DISTRESS…','');fetch('/node-alert?node=WEB-FLIGHT&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30').then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.text()}).then(function(t){write('DISTRESS → '+t);status('Distress accepted','okbox')}).catch(function(e){status('Trigger failed: '+e.message,'err')}).finally(function(){setTimeout(function(){b.disabled=false},700)})};$('fit').onclick=fit;$('follow').onclick=function(){follow=!follow;$('follow').textContent='FOLLOW: '+(follow?'ON':'OFF');if(!follow)viewer.trackedEntity=undefined;else if(aircraft)viewer.trackedEntity=aircraft};$('top').onclick=function(){if(last&&last.lat!=null)viewer.camera.flyTo({destination:pos(last.lat,last.lon,1200),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}})};$('reset').onclick=function(){viewer.trackedEntity=undefined;viewer.camera.flyTo({destination:pos(21.1466,79.0889,5000),duration:1})};init()})();
</script></body></html>'''
