"""Geographic 3D drone flight simulation page for VanniKawachh.

This page is presentation-facing: the deployed /drone_state feed is the single
mission source, while Cesium supplies the geographic 3D world, terrain/buildings
when available, and the aircraft model.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Autonomous Drone Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@latest/Build/Cesium/Widgets/widgets.css">
<style>
:root{--bg:#071018;--panel:#0a151e;--line:#27414f;--text:#edf7fa;--muted:#8da6b4;--green:#35e2b3;--amber:#ffb34c;--red:#ff6875;--blue:#68b5ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 430px;width:100vw;height:100vh}
#world{position:relative;min-width:0;min-height:0}.cesium-viewer,.cesium-widget,.cesium-widget canvas{width:100%;height:100%}.cesium-viewer-bottom,.cesium-viewer-animationContainer,.cesium-viewer-timelineContainer{display:none!important}
.top{position:absolute;z-index:10;left:12px;right:12px;top:12px;display:flex;justify-content:space-between;gap:10px;pointer-events:none}.pill{background:#06131ce8;border:1px solid var(--line);border-radius:999px;padding:8px 12px;backdrop-filter:blur(8px)}.pill b{color:#fff}.live{color:var(--green)}
#side{overflow:auto;background:#07121bf8;border-left:1px solid var(--line);padding:13px}.title{font-size:21px;font-weight:900}.sub,.note{color:var(--muted);font-size:10px;line-height:1.5}.card{background:linear-gradient(180deg,#0e1f2a,#09151d);border:1px solid var(--line);border-radius:12px;padding:11px;margin:9px 0}.lab{font-size:10px;color:var(--muted);font-weight:800;letter-spacing:.1em}.big{font-size:27px;font-weight:900;margin:3px 0}.row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.val{font-weight:800;text-align:right}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}
.seq{display:grid;gap:4px;margin-top:6px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;background:#09151d;color:#667d89}.step.active{border-color:#8d6427;background:#211b10;color:#ffdba0;font-weight:800}.step.done{border-color:#286c5a;background:#0c211b;color:#adf4e1}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#394c55;margin-right:7px}.step.active .dot{background:var(--amber)}.step.done .dot{background:var(--green)}
.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:3px;align-items:center}.node{padding:7px 3px;text-align:center;font-size:8px;border:1px solid #284354;border-radius:7px;background:#0b1921}.node.active{border-color:var(--green);box-shadow:0 0 12px #35e2b322}.arr{color:var(--green)}
.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);border-radius:8px;padding:10px;background:#122432;color:#fff;font-weight:800;cursor:pointer}.btn.primary{background:#0e2c24;border-color:#296d5a}.btn.warnBtn{background:#2a2113;border-color:#705126}.btn:hover{filter:brightness(1.12)}
svg{width:100%;height:165px;background:#08131b;border:1px solid #223b49;border-radius:9px}.t{fill:#bed2d9;font-size:9px;font-weight:800}.arm{stroke:#536f7a;stroke-width:7;stroke-linecap:round}.m{fill:#192a33;stroke:#6a8791}.fc{fill:#173c48;stroke:var(--green)}.bat{fill:#3d2d17;stroke:var(--amber)}.gps{fill:#113126;stroke:var(--green)}.comp{fill:#172c3d;stroke:var(--blue)}.cam{fill:#192a34;stroke:var(--blue)}.pay{fill:#312517;stroke:var(--amber)}.wire{stroke:#4f6d7a;stroke-width:2;fill:none}
#log{height:85px;overflow:auto;background:#061018;border:1px solid #19303d;border-radius:7px;padding:6px;font:9px/1.5 ui-monospace,Consolas,monospace;color:#8fb9c7}
.badge{position:absolute;z-index:20;bottom:14px;left:14px;background:#07131ee8;border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:10px}.badge b{color:var(--green)}
@media(max-width:900px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:30;right:0;top:0;bottom:0;width:min(430px,95vw);box-shadow:-20px 0 40px #000b}}
</style>
</head>
<body>
<div id="app">
<section id="world"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · AUTONOMOUS DRONE FLIGHT</div><div class="pill"><span class="live">●</span> <b id="source">LIVE HUB</b></div></div><div id="cesium" style="width:100%;height:100%"></div><div class="badge">WORLD: <b id="worldStatus">loading terrain / 3D buildings…</b></div></section>
<aside id="side">
<div class="title">Autonomous Drone Flight</div>
<div class="sub">This is the geographic 3D mission view. The aircraft, route, camera, telemetry, payload sequence and hardware indicators all react to the deployed <b>/drone_state</b> feed produced by the Wokwi/ESP32 → hub pipeline.</div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude AGL</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Distance remaining</span><span id="dist" class="val">—</span></div><div class="row"><span>Real-world ETA</span><span id="eta" class="val">—</span></div><div class="row"><span>Playback</span><span id="playback" class="val">10× presentation</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger received</div><div class="step" id="s2"><span class="dot"></span>Arm / spin four rotors</div><div class="step" id="s3"><span class="dot"></span>Takeoff</div><div class="step" id="s4"><span class="dot"></span>Navigate to distress GPS</div><div class="step" id="s5"><span class="dot"></span>Hover at incident</div><div class="step" id="s6"><span class="dot"></span>Open payload servo</div><div class="step" id="s7"><span class="dot"></span>Drop health kit</div><div class="step" id="s8"><span class="dot"></span>RTL / land</div></div></div>
<div class="card"><div class="lab">AIRCRAFT SYSTEMS</div><div class="row"><span>4 × BLDC / ESC</span><span id="motors" class="val ok">OFF</span></div><div class="row"><span>Flight controller</span><span class="val ok">CONNECTED</span></div><div class="row"><span>GPS / compass</span><span class="val ok">LOCKED</span></div><div class="row"><span>Companion / LoRa</span><span class="val ok">ONLINE</span></div><div class="row"><span>Camera</span><span id="cam" class="val ok">STANDBY</span></div><div class="row"><span>Payload servo</span><span id="servo" class="val">CLOSED</span></div><div class="row"><span>Health kit</span><span id="kit" class="val">SECURED</span></div></div>
<div class="card"><div class="lab">ON-BOARD HARDWARE / CONNECTIONS</div>
<svg viewBox="0 0 400 165"><line class="arm" x1="150" y1="70" x2="55" y2="30"/><line class="arm" x1="250" y1="70" x2="345" y2="30"/><line class="arm" x1="150" y1="90" x2="55" y2="135"/><line class="arm" x1="250" y1="90" x2="345" y2="135"/><circle class="m" cx="55" cy="30" r="16"/><circle class="m" cx="345" cy="30" r="16"/><circle class="m" cx="55" cy="135" r="16"/><circle class="m" cx="345" cy="135" r="16"/><rect class="fc" x="165" y="54" width="70" height="50" rx="8"/><text class="t" x="178" y="77">FLIGHT</text><text class="t" x="175" y="91">CONTROLLER</text><rect class="gps" x="178" y="4" width="44" height="17" rx="4"/><text class="t" x="188" y="16">GPS</text><rect class="bat" x="173" y="114" width="55" height="22" rx="5"/><text class="t" x="188" y="129">LiPo</text><rect class="comp" x="276" y="103" width="75" height="24" rx="5"/><text class="t" x="286" y="118">COMP / LoRa</text><rect class="cam" x="160" y="17" width="29" height="18" rx="4"/><text class="t" x="196" y="30">CAM</text><rect class="pay" x="210" y="140" width="80" height="18" rx="4"/><text class="t" x="222" y="153">SERVO + KIT</text><path class="wire" d="M180 21 L190 54 M222 21 L214 54 M165 73 L55 30 M235 73 L345 30 M165 93 L55 135 M235 93 L345 135 M200 104 L200 114 M226 136 L245 140 M235 90 L276 112"/><text class="t" x="18" y="16">M1</text><text class="t" x="354" y="16">M2</text><text class="t" x="18" y="156">M3</text><text class="t" x="354" y="156">M4</text></svg>
<div class="note">LiPo → power distribution/ESCs → four BLDC motors. GPS/compass → flight controller. Companion/LoRa → mission communications. Servo → health-kit bay. Camera → visual verification.</div></div>
<div class="card"><div class="lab">CONTROL SIGNAL</div><div class="chain"><div class="node" id="n1">ESP32<br>SENSOR</div><div class="arr">→</div><div class="node" id="n2">HUB<br>DISPATCH</div><div class="arr">→</div><div class="node" id="n3">FLIGHT<br>CONTROLLER</div><div class="arr">→</div><div class="node" id="n4">ESCs /<br>SERVO</div></div></div>
<div class="buttons"><button id="live" class="btn primary">LIVE HUB</button><button id="trigger" class="btn">TEST HUB DISTRESS</button><button id="fit" class="btn">FIT MISSION</button><button id="reset" class="btn warnBtn">RESET VIEW</button></div>
<div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div>
<div class="note">The world/aircraft layer is geographic visualization. The backend supplies the mission/GPS state. ArduPilot SITL remains the separate flight-physics validation layer.</div>
</aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@latest/Build/Cesium/Cesium.js"></script>
<script>
const $=id=>document.getElementById(id);
const log=m=>{const e=$('log');e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};
let viewer,aircraft,homeEntity,targetEntity,routeEntity,routeArc,live=true,timer=null,lastMission=null,lastState='IDLE',last=null,follow=true,terrainReady=false;
const droneModel='https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone.glb';
const fallbackModel='https://cdn.jsdelivr.net/gh/CesiumGS/cesium@main/Apps/SampleData/models/CesiumDrone/CesiumDrone.glb';
const cart=(lat,lon,h=0)=>Cesium.Cartesian3.fromDegrees(+lon,+lat,+h);
const distFmt=m=>m==null?'—':m<1000?Math.round(m)+' m':(m/1000).toFixed(2)+' km';
const timeFmt=s=>s==null?'—':s>=3600?Math.floor(s/3600)+'h '+Math.floor((s%3600)/60)+'m':s>=60?Math.floor(s/60)+'m '+(Math.round(s)%60)+'s':Math.round(s)+'s';
function hav(a,b){if(!a||!b)return 0;const R=6371000,r=x=>x*Math.PI/180,d1=r(b[0]-a[0]),d2=r(b[1]-a[1]);const x=Math.sin(d1/2)**2+Math.cos(r(a[0]))*Math.cos(r(b[0]))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function bearing(a,b){const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))}
function setOrientation(d){if(!d||d.lat==null||!d.target)return;const q=Cesium.Transforms.headingPitchRollQuaternion(cart(d.lat,d.lon,15),new Cesium.HeadingPitchRoll(bearing([d.lat,d.lon],d.target),0,0));aircraft.orientation=q}
function setChecklist(s){const all=['s1','s2','s3','s4','s5','s6','s7','s8'];all.forEach(id=>$(id).className='step');const done={s1:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','COMPLETED'],s4:['HOVERING','DELIVERING','RTL','COMPLETED'],s5:['DELIVERING','RTL','COMPLETED'],s6:['RTL','COMPLETED'],s7:['RTL','COMPLETED'],s8:['COMPLETED']};for(const [id,ss] of Object.entries(done))if(ss.includes(s))$(id).className='step done';const a={TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8'}[s];if(a)$(a).className='step active';if(s==='DELIVERING')$('s7').className='step active';if(s==='COMPLETED')all.forEach(id=>$(id).className='step done')}
function hardware(s,d){const f=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL'].includes(s);$('motors').textContent=f?'SPINNING':'OFF';$('motors').className='val '+(f?'warn':'ok');$('cam').textContent=f?'ACTIVE':'STANDBY';$('servo').textContent=s==='DELIVERING'?'OPEN':'CLOSED';$('kit').textContent=d&&d.kit_dropped?'DROPPED':'SECURED';['n1','n2','n3','n4'].forEach(id=>$(id).classList.remove('active'));if(s!=='IDLE')$('n1').classList.add('active');if(s!=='IDLE')$('n2').classList.add('active');if(f)$('n3').classList.add('active');if(['DELIVERING','RTL','COMPLETED'].includes(s))$('n4').classList.add('active')}
function apply(d){if(!d)return;last=d;const s=d.state||'IDLE';$('state').textContent=s;$('state').className='big '+(['TAKEOFF','ENROUTE','RTL'].includes(s)?'warn':s==='FAILED'?'bad':'ok');$('mission').textContent=d.mission_id||'—';$('gps').textContent=d.lat!=null?`${Number(d.lat).toFixed(5)}, ${Number(d.lon).toFixed(5)}`:'—';const speed=['ENROUTE','RTL'].includes(s)?15:['TAKEOFF'].includes(s)?4:0;const alt=['ENROUTE','HOVERING','DELIVERING','RTL'].includes(s)?15:s==='TAKEOFF'?5:0;$('speed').textContent=speed.toFixed(1)+' m/s';$('alt').textContent=alt.toFixed(1)+' m';$('dist').textContent=d.distance_m!=null?distFmt(d.distance_m):'—';$('eta').textContent=timeFmt(d.eta_reach_s);$('playback').textContent=(d.sim_time_accel?d.sim_time_accel+'× presentation':'presentation');$('source').textContent='LIVE HUB';hardware(s,d);setChecklist(s);if(d.home){homeEntity.position=cart(d.home[0],d.home[1],0)}if(d.target){targetEntity.position=cart(d.target[0],d.target[1],0)}if(d.home&&d.target){routeEntity.polyline.positions=sampleGreatCircle(d.home,d.target,40)}if(d.lat!=null){const h=alt;aircraft.position=cart(d.lat,d.lon,h);setOrientation(d)}if(s==='ENROUTE'||s==='HOVERING'||s==='DELIVERING'||s==='RTL')viewer.trackedEntity=aircraft;if(s==='COMPLETED')viewer.trackedEntity=undefined;if(d.mission_id&&d.mission_id!==lastMission){lastMission=d.mission_id;log('Mission '+d.mission_id+' received');fitMission()}if(s!==lastState){lastState=s;log('State → '+s)}}
function sampleGreatCircle(a,b,n){const pts=[];for(let i=0;i<=n;i++){const f=i/n;const la=a[0]+(b[0]-a[0])*f;const lo=a[1]+(b[1]-a[1])*f;pts.push(cart(la,lo,12))}return pts}
function fitMission(){if(!last||!last.home||!last.target)return;const mid=Cesium.Cartesian3.midpoint(cart(last.home[0],last.home[1],0),cart(last.target[0],last.target[1],0),new Cesium.Cartesian3());const distance=Math.max(2500,hav(last.home,last.target)*1.25);viewer.camera.flyTo({destination:Cesium.Cartesian3.fromRadians(Cesium.Cartographic.fromCartesian(mid).longitude,Cesium.Cartographic.fromCartesian(mid).latitude,Math.max(2000,distance)),orientation:{heading:0,pitch:Cesium.Math.toRadians(-65),roll:0},duration:1.2})}
async function init(){viewer=new Cesium.Viewer('cesium',{animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,infoBox:false,selectionIndicator:false,fullscreenButton:false,shouldAnimate:false});viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',maximumLevel:19,credit:'© OpenStreetMap contributors'}));
try{if(Cesium.createWorldTerrainAsync){viewer.terrainProvider=await Cesium.createWorldTerrainAsync();terrainReady=true;$('worldStatus').textContent='terrain enabled'}else{$('worldStatus').textContent='terrain fallback'}}catch(e){$('worldStatus').textContent='terrain fallback'}
try{if(Cesium.createOsmBuildingsAsync){const b=await Cesium.createOsmBuildingsAsync();viewer.scene.primitives.add(b);$('worldStatus').textContent=terrainReady?'terrain + 3D buildings':'3D buildings enabled'} }catch(e){if(terrainReady)$('worldStatus').textContent='terrain enabled · buildings fallback'}
viewer.scene.globe.enableLighting=true;viewer.scene.globe.depthTestAgainstTerrain=false;viewer.scene.screenSpaceCameraController.enableCollisionDetection=false;
aircraft=viewer.entities.add({name:'VanniKawachh Response Drone',position:cart(21.1188,79.0195,0),model:{uri:droneModel,scale:1.8,minimumPixelSize:100,maximumScale:3000,shadows:Cesium.ShadowMode.ENABLED},label:{text:'VANNIKAWACHH DRONE',font:'12px sans-serif',style:Cesium.LabelStyle.FILL_AND_OUTLINE,fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-50)}});
// If the external aircraft model cannot be loaded, Cesium will still render the fallback model below via a replacement hook.
aircraft.model.readyEvent.addEventListener(()=>log('Aircraft model loaded'));homeEntity=viewer.entities.add({name:'Drone Base',position:cart(21.1188,79.0195),point:{pixelSize:11,color:Cesium.Color.CYAN,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DRONE BASE',font:'11px sans-serif',style:Cesium.LabelStyle.FILL_AND_OUTLINE,fillColor:Cesium.Color.CYAN,outlineColor:Cesium.Color.BLACK,outlineWidth:3,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-14)}});targetEntity=viewer.entities.add({name:'Distress Target',position:cart(21.1466,79.0889),point:{pixelSize:13,color:Cesium.Color.RED,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DISTRESS / HEALTH KIT',font:'11px sans-serif',style:Cesium.LabelStyle.FILL_AND_OUTLINE,fillColor:Cesium.Color.RED,outlineColor:Cesium.Color.BLACK,outlineWidth:3,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-14)}});routeEntity=viewer.entities.add({name:'Mission Route',polyline:{positions:[cart(21.1188,79.0195,12),cart(21.1466,79.0889,12)],width:4,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.18,color:Cesium.Color.CYAN}),clampToGround:false}});
viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(79.0889,21.1466,18000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-65),roll:0},duration:1});log('World ready · waiting for deployed /drone_state');poll()}
async function poll(){if(!live)return;try{const r=await fetch('/drone_state',{cache:'no-store'});if(r.ok)apply(await r.json())}catch(e){$('source').textContent='HUB OFFLINE'}timer=setTimeout(poll,300)}
$('live').onclick=()=>{live=true;$('source').textContent='LIVE HUB';poll()};$('fit').onclick=()=>fitMission();$('reset').onclick=()=>{viewer.trackedEntity=undefined;viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(79.0889,21.1466,18000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-65),roll:0},duration:1});log('Camera reset')};$('trigger').onclick=async()=>{try{const q=`/node-alert?node=DRONE-SIM&lat=21.1466&lon=79.0889&event=1&conf=0.99&pir=1&light=30`;const r=await fetch(q,{method:'POST'});const j=await r.json();log(j.dispatched?'TEST DISPATCH '+j.mission_id:'Hub response '+JSON.stringify(j));live=true;poll()}catch(e){log('Trigger failed: '+e.message)}};
init();
</script></body></html>'''
