"""Final geographic flight viewer for VanniKawachh.

Uses the deployed /drone_state feed as the only mission source. The browser camera
is free by default, with explicit fit/follow/top-down controls. The aircraft shell
is a direct GLB asset and four rotor markers are independently animated from the
same motor_rpm telemetry.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | Geographic 3D Flight</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Widgets/widgets.css">
<style>
:root{--bg:#061018;--panel:#07131c;--line:#284452;--txt:#edf7fa;--muted:#8da5b4;--green:#35e2b3;--amber:#ffb34c;--red:#ff6875;--blue:#68b8ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Inter,Segoe UI,Arial,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 430px;width:100vw;height:100vh}#world{position:relative;min-width:0;min-height:0}#cesium{position:absolute;inset:0}.top{position:absolute;z-index:10;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;pointer-events:none}.pill{background:#07131ee8;border:1px solid var(--line);border-radius:999px;padding:8px 12px}.live{color:var(--green)}
#side{overflow:auto;background:#07121bf8;border-left:1px solid var(--line);padding:13px}.title{font-size:21px;font-weight:900}.sub,.note{font-size:10px;color:var(--muted);line-height:1.5}.card{background:linear-gradient(180deg,#0e1f2a,#09151d);border:1px solid var(--line);border-radius:12px;padding:11px;margin:9px 0}.lab{font-size:10px;color:var(--muted);letter-spacing:.1em;font-weight:900}.big{font-size:28px;font-weight:900;margin:2px 0}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.val{font-weight:800;text-align:right}
.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;color:#667e8b;background:#09151d}.step.active{border-color:#916729;background:#211a10;color:#ffdfa0;font-weight:800}.step.done{border-color:#286b5a;background:#0c211b;color:#aef4e1}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#394d57;margin-right:7px}.step.active .dot{background:var(--amber)}.step.done .dot{background:var(--green)}
.chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:3px;align-items:center}.node{padding:7px 3px;text-align:center;font-size:8px;border:1px solid #294553;border-radius:7px;background:#0a1922}.node.active{border-color:var(--green);box-shadow:0 0 12px #35e2b322}.arr{color:var(--green)}
.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{border:1px solid var(--line);border-radius:8px;padding:10px;background:#122432;color:#fff;font-weight:900;cursor:pointer}.btn.primary{background:#0d2d25;border-color:#286b5a}.btn.warn{background:#2a2113;border-color:#705025}.btn:disabled{opacity:.45;cursor:wait}.btn:hover:not(:disabled){filter:brightness(1.1)}
#status{padding:8px 10px;border:1px solid #1c3744;border-radius:8px;background:#061016;font-size:10px;min-height:18px}.okbox{border-color:#286b5a!important;color:#aef4e1}.errbox{border-color:#913443!important;color:#ffb8c1}.busybox{border-color:#916729!important;color:#ffe0a1}#log{height:84px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px/1.45 ui-monospace,Consolas,monospace;color:#8fb9c7}
.help{position:absolute;z-index:10;left:14px;bottom:14px;background:#07131ee8;border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:10px;color:var(--muted)}
@media(max-width:900px){#app{grid-template-columns:1fr}#side{position:absolute;z-index:30;right:0;top:0;bottom:0;width:min(430px,95vw);box-shadow:-20px 0 50px #000c}}
</style>
</head>
<body>
<div id="app">
<section id="world"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · GEOGRAPHIC 3D FLIGHT</div><div class="pill"><span class="live">●</span> <b id="source">CHECKING…</b></div></div><div id="cesium"></div><div class="help">Orbit with left drag · pan with right drag · zoom with wheel · start with <b>FIT ROUTE</b></div></section>
<aside id="side">
<div class="title">Autonomous Mission Flight</div><div class="sub">The aircraft, route, altitude, speed, RPM and payload sequence read the same deployed <b>/drone_state</b> mission created by the Wokwi/ESP32 distress path.</div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Motor RPM</span><span id="rpm" class="val">0</span></div><div class="row"><span>Distance remaining</span><span id="dist" class="val">—</span></div><div class="row"><span>ETA</span><span id="eta" class="val">—</span></div></div>
<div class="card"><div class="lab">FLIGHT SEQUENCE</div><div class="seq"><div class="step" id="s1"><span class="dot"></span>Distress trigger</div><div class="step" id="s2"><span class="dot"></span>Arm / rotor spool</div><div class="step" id="s3"><span class="dot"></span>Vertical takeoff</div><div class="step" id="s4"><span class="dot"></span>Cruise to target</div><div class="step" id="s5"><span class="dot"></span>Hover</div><div class="step" id="s6"><span class="dot"></span>Open payload</div><div class="step" id="s7"><span class="dot"></span>Drop health kit</div><div class="step" id="s8"><span class="dot"></span>RTL / land</div></div></div>
<div class="card"><div class="lab">SYSTEMS</div><div class="row"><span>Motors / props</span><span id="motors" class="val ok">OFF</span></div><div class="row"><span>Flight controller</span><span class="val ok">PIXHAWK / ARDUPILOT</span></div><div class="row"><span>GPS / compass</span><span class="val ok">INPUT</span></div><div class="row"><span>Companion / LoRa</span><span id="link" class="val">STANDBY</span></div><div class="row"><span>Payload servo</span><span id="servo" class="val">CLOSED</span></div><div class="row"><span>Health kit</span><span id="kit" class="val">SECURED</span></div></div>
<div class="card"><div class="lab">CONTROL CHAIN</div><div class="chain"><div id="n1" class="node">ESP32<br>SENSOR</div><div class="arr">→</div><div id="n2" class="node">HUB<br>DISPATCH</div><div class="arr">→</div><div id="n3" class="node">PIXHAWK<br>ARDUPILOT</div><div class="arr">→</div><div id="n4" class="node">ESCs<br>+ SERVO</div></div></div>
<div class="buttons"><button id="live" class="btn primary">LIVE HUB</button><button id="trigger" class="btn">TEST DISTRESS</button><button id="fit" class="btn">FIT ROUTE</button><button id="follow" class="btn">FOLLOW: OFF</button><button id="topdown" class="btn">TOP DOWN</button><button id="reset" class="btn warn">RESET VIEW</button></div>
<div id="status">Loading geographic viewer…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log"></div></div><div class="note">The geographic browser view is the visual mission layer. True aerodynamic flight validation remains the ArduPilot SITL + Gazebo layer described by the project.</div>
</aside></div>
<script src="https://cdn.jsdelivr.net/npm/cesium@1.132.0/Build/Cesium/Cesium.js"></script>
<script>
(() => {
const $=id=>document.getElementById(id),log=m=>{const e=$("log");e.innerHTML+=`<div>${new Date().toLocaleTimeString()} · ${m}</div>`;e.scrollTop=e.scrollHeight};
const setStatus=(m,k)=>{const e=$("status");e.textContent=m;e.className=k==='ok'?'okbox':k==='err'?'errbox':k==='busy'?'busybox':''};
const cart=(lat,lon,h=0)=>Cesium.Cartesian3.fromDegrees(+lon,+lat,+h);
const fmtDist=m=>m==null?'—':m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`;
const fmtTime=s=>s==null?'—':s>=3600?`${Math.floor(s/3600)}h ${Math.floor((s%3600)/60)}m`:s>=60?`${Math.floor(s/60)}m ${Math.round(s)%60}s`:`${Math.round(s)}s`;
function bearing(a,b){const p1=Cesium.Math.toRadians(a[0]),p2=Cesium.Math.toRadians(b[0]),dl=Cesium.Math.toRadians(b[1]-a[1]);return Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl));}
function offset(lat,lon,north,east,h){return cart(lat+north/111320,lon+east/(111320*Math.cos(Cesium.Math.toRadians(lat))),h)}
let viewer,drone,homeEntity,targetEntity,routeEntity,trailEntity,last,lastState='IDLE',lastMission=null,timer,follow=false,routeReady=false,rotorAngle=0,lastFrame=performance.now(),rotors=[];
function checklist(s){const done={s1:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s4:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s5:['HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s6:['DELIVERING','RTL','LANDING','COMPLETED'],s7:['RTL','LANDING','COMPLETED'],s8:['RTL','LANDING','COMPLETED']};Object.entries(done).forEach(([id,states])=>$(id).className='step'+(states.includes(s)?' done':''));const a={ARMING:'s2',TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8',LANDING:'s8'}[s];if(a)$(a).className='step active'}
function applyState(d){last=d;const s=d?.state||'IDLE';$("state").textContent=s;$("state").className='big '+(s==='FAILED'?'bad':(['TAKEOFF','ENROUTE','RTL','LANDING'].includes(s)?'warn':'ok'));$("mission").textContent=d?.mission_id||'—';$("gps").textContent=d?.lat!=null?`${Number(d.lat).toFixed(5)}, ${Number(d.lon).toFixed(5)}`:'—';$("speed").textContent=`${Number(d?.speed_ms||0).toFixed(1)} m/s`;$("alt").textContent=`${Number(d?.altitude_m||0).toFixed(1)} m`;$("rpm").textContent=Math.round(Number(d?.motor_rpm||0)).toLocaleString();$("dist").textContent=fmtDist(d?.distance_m);$("eta").textContent=fmtTime(d?.eta_reach_s);const armed=['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING'].includes(s);$("motors").textContent=armed?'RUNNING':'OFF';$("link").textContent=s==='IDLE'?'STANDBY':'ACTIVE';$("servo").textContent=s==='DELIVERING'?'OPEN':'CLOSED';$("kit").textContent=d?.kit_dropped?'DROPPED':'SECURED';['n1','n2','n3','n4'].forEach(id=>$(id).classList.remove('active'));if(s!=='IDLE')$("n1").classList.add('active');if(s!=='IDLE')$("n2").classList.add('active');if(armed)$("n3").classList.add('active');if(['DELIVERING','RTL','LANDING','COMPLETED'].includes(s))$("n4").classList.add('active');checklist(s);if(s!==lastState){log('STATE → '+s);lastState=s}if(d?.mission_id&&d.mission_id!==lastMission){log('MISSION '+d.mission_id);lastMission=d.mission_id}}
function updateWorld(d){if(!viewer||d?.lat==null)return;drone.position=cart(d.lat,d.lon,d.altitude_m||0);drone.orientation=Cesium.Transforms.headingPitchRollQuaternion(drone.position,new Cesium.HeadingPitchRoll(d.heading_deg==null?(d.target?bearing([d.lat,d.lon],d.target):0):Cesium.Math.toRadians(d.heading_deg),0,0));if(d.home&&d.target){const h=cart(d.home[0],d.home[1],0),t=cart(d.target[0],d.target[1],0);if(!homeEntity)homeEntity=viewer.entities.add({name:'SAFE LANDING / HOME',position:h,ellipse:{semiMajorAxis:20,semiMinorAxis:20,material:Cesium.Color.CYAN.withAlpha(.15),outline:true,outlineColor:Cesium.Color.CYAN}});if(!targetEntity)targetEntity=viewer.entities.add({name:'DISTRESS',position:t,point:{pixelSize:14,color:Cesium.Color.RED,outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:'DISTRESS',font:'12px sans-serif',fillColor:Cesium.Color.RED,showBackground:true,backgroundColor:Cesium.Color.BLACK.withAlpha(.55),pixelOffset:new Cesium.Cartesian2(0,-24)}});if(!routeEntity)routeEntity=viewer.entities.add({name:'MISSION ROUTE',polyline:{positions:[h,t],width:4,material:Cesium.Color.CYAN}});routeReady=true;const baseOffsets=[[1.25,.9],[1.25,-.9],[-1.25,.9],[-1.25,-.9]];rotors.forEach((r,i)=>{const p=offset(d.lat,d.lon,baseOffsets[i][0],baseOffsets[i][1],Number(d.altitude_m||0)+.12);r.one.position=p;r.two.position=p;r.one.ellipse.rotation=rotorAngle;r.two.ellipse.rotation=rotorAngle+Math.PI/2});if(trailEntity){const arr=trailEntity.polyline.positions.getValue(Cesium.JulianDate.now())||[];arr.push(drone.position);if(arr.length>400)arr.shift();trailEntity.polyline.positions=arr;}}}
function fit(){if(!routeReady||!last?.home||!last?.target){setStatus('No mission route yet — trigger a distress first','busy');return}const hs=last.home,ts=last.target;const minLat=Math.min(hs[0],ts[0]),maxLat=Math.max(hs[0],ts[0]),minLon=Math.min(hs[1],ts[1]),maxLon=Math.max(hs[1],ts[1]);const padLat=Math.max(.006,(maxLat-minLat)*.25),padLon=Math.max(.006,(maxLon-minLon)*.25);viewer.trackedEntity=undefined;follow=false;$("follow").textContent='FOLLOW: OFF';viewer.camera.flyTo({destination:Cesium.Rectangle.fromDegrees(minLon-padLon,minLat-padLat,maxLon+padLon,maxLat+padLat),duration:1.2});setStatus('Full route fitted — free camera','ok')}
async function readHub(){try{const r=await fetch('/drone_state?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();$("source").textContent='HUB ONLINE';setStatus('Connected to /drone_state','ok');applyState(d);updateWorld(d);return d}catch(e){$("source").textContent='HUB ERROR';setStatus('Hub error: '+e.message,'err');return null}}
async function trigger(){const b=$("trigger");b.disabled=true;setStatus('Sending TEST DISTRESS…','busy');try{const r=await fetch('/node-alert?node=WEB-FLIGHT&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30',{cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error('HTTP '+r.status+': '+text);log('DISTRESS → '+text);setStatus('Distress accepted — mission starting','ok');poll()}catch(e){setStatus('Trigger failed: '+e.message,'err');log('TRIGGER ERROR → '+e.message)}finally{setTimeout(()=>b.disabled=false,700)}}
function poll(){readHub().finally(()=>timer=setTimeout(poll,600))}
async function init(){viewer=new Cesium.Viewer('cesium',{imageryProvider:new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors'}),terrainProvider:new Cesium.EllipsoidTerrainProvider(),baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,infoBox:false,selectionIndicator:false});viewer.scene.globe.enableLighting=true;viewer.scene.screenSpaceCameraController.enableZoom=true;viewer.scene.screenSpaceCameraController.enableRotate=true;viewer.scene.screenSpaceCameraController.enableTranslate=true;viewer.scene.screenSpaceCameraController.enableTilt=true;try{viewer.scene.primitives.add(await Cesium.createOsmBuildingsAsync());setStatus('OSM + 3D buildings ready','ok')}catch(e){setStatus('OSM map ready — 3D buildings unavailable','ok')}drone=viewer.entities.add({name:'VanniKawachh Drone',position:cart(21.1466,79.0889,0),model:{uri:'https://cdn.jsdelivr.net/gh/amvlab/aircraft-models@main/models/drone_nologo.glb',minimumPixelSize:90,maximumScale:250,scale:1.15,shadows:Cesium.ShadowMode.ENABLED}});trailEntity=viewer.entities.add({name:'FLIGHT TRAIL',polyline:{positions:[],width:2,material:Cesium.Color.LIME.withAlpha(.9)}});for(let i=0;i<4;i++){const one=viewer.entities.add({position:cart(21.1466,79.0889,.1),ellipse:{semiMajorAxis:.72,semiMinorAxis:.10,material:Cesium.Color.WHITE.withAlpha(.88),outline:true,outlineColor:Cesium.Color.CYAN.withAlpha(.75),rotation:0}});const two=viewer.entities.add({position:cart(21.1466,79.0889,.11),ellipse:{semiMajorAxis:.72,semiMinorAxis:.10,material:Cesium.Color.WHITE.withAlpha(.55),outline:false,rotation:Math.PI/2}});rotors.push({one,two})}poll();}
$("live").onclick=()=>{setStatus('Connecting to deployed hub…','busy');poll()};$("trigger").onclick=trigger;$("fit").onclick=fit;$("follow").onclick=()=>{if(follow){viewer.trackedEntity=undefined;follow=false;$("follow").textContent='FOLLOW: OFF';setStatus('Free camera restored','ok')}else{viewer.trackedEntity=drone;follow=true;$("follow").textContent='FOLLOW: ON';setStatus('Following aircraft — wheel still zooms','ok')}};$("topdown").onclick=()=>{if(routeReady&&last?.home&&last?.target){const mid=Cesium.Cartesian3.midpoint(cart(last.home[0],last.home[1],0),cart(last.target[0],last.target[1],0),new Cesium.Cartesian3());viewer.camera.lookAt(mid,new Cesium.HeadingPitchRange(0,Cesium.Math.toRadians(-90),Math.max(250,Cesium.Cartesian3.distance(cart(last.home[0],last.home[1],0),cart(last.target[0],last.target[1],0))*1.2));setStatus('Top-down route view','ok')}};$("reset").onclick=()=>{if(last?.home){viewer.trackedEntity=undefined;follow=false;$("follow").textContent='FOLLOW: OFF';viewer.camera.flyTo({destination:cart(last.home[0],last.home[1],2500),duration:.8});setStatus('View reset to launch area','ok')}else fit()};
function frame(now){const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;rotorAngle+=Number(last?.motor_rpm||0)*Math.PI*2/60*dt;requestAnimationFrame(frame)}requestAnimationFrame(frame);
init().catch(e=>{setStatus('Viewer init failed: '+e.message,'err');log('INIT ERROR → '+e.message)});
})();
</script>
</body></html>'''
