"""SIMNET/ArduPilot flight console for VanniKawachh.

Render is the mission/control surface. SIMNET is the high-fidelity 3D physics
engine when SIMNET_HOST/SIMNET_PORT are configured. The console deliberately
stops pretending that a browser animation is aerodynamic physics.
"""
from fastapi.responses import HTMLResponse


def attach(app):
    @app.get("/drone-flight", response_class=HTMLResponse)
    def drone_flight_page():
        return HTML


HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>VanniKawachh | SIMNET / ArduPilot Flight Lab</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
:root{--bg:#050b10;--panel:#08141c;--line:#2a4653;--txt:#edf7fa;--muted:#91a8b5;--green:#35e2b3;--amber:#ffb34c;--red:#ff6875;--blue:#68b8ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--txt);font:12px Segoe UI,Arial,sans-serif}#app{display:grid;grid-template-columns:minmax(0,1fr) 440px;height:100vh}#map{position:relative;min-width:0;background:#09131a}#mapCanvas{position:absolute;inset:0}.top{position:absolute;z-index:20;left:12px;right:12px;top:12px;display:flex;justify-content:space-between}.pill{background:#07131ee8;border:1px solid var(--line);border-radius:999px;padding:9px 12px}.live{color:var(--green)}#side{overflow:auto;background:#07121bf8;border-left:1px solid var(--line);padding:13px}.title{font-size:22px;font-weight:900}.sub,.note{font-size:10px;line-height:1.55;color:var(--muted)}.card{border:1px solid var(--line);border-radius:12px;background:linear-gradient(180deg,#0d1d27,#08131c);padding:11px;margin:9px 0}.lab{font-size:10px;letter-spacing:.1em;color:var(--muted);font-weight:900}.big{font-size:28px;font-weight:900}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.row{display:flex;justify-content:space-between;gap:12px;margin:7px 0}.val{font-weight:900;text-align:right}.btns{display:grid;grid-template-columns:1fr 1fr;gap:7px}.btn{padding:10px;border-radius:8px;border:1px solid var(--line);background:#122432;color:#fff;font-weight:900;cursor:pointer}.btn.primary{background:#0d2d25;border-color:#286b5a}.btn.warn{background:#2a2113;border-color:#705025}.btn:disabled{opacity:.45}.status{padding:9px;border:1px solid var(--line);border-radius:8px;background:#061016;font-size:10px}.good{border-color:#286b5a;color:#b0f5e3}.err{border-color:#913443;color:#ffbac1}.seq{display:grid;gap:4px}.step{padding:7px 9px;border:1px solid #1d3440;border-radius:8px;color:#677f8c}.step.done{background:#0c211b;border-color:#286b5a;color:#b0f5e3}.step.active{background:#211a10;border-color:#916729;color:#ffe0a1}.log{height:82px;overflow:auto;background:#051017;border:1px solid #17303d;border-radius:7px;padding:6px;font:9px/1.45 monospace;color:#8fb9c7}.simnet{display:flex;gap:8px;align-items:center;padding:10px 11px;border-radius:9px;background:#07131a;border:1px solid #284452}.dot{width:9px;height:9px;border-radius:50%;background:#657d89}.dot.on{background:var(--green);box-shadow:0 0 10px #35e2b355}.small{font-size:9px;color:var(--muted)}
@media(max-width:900px){#app{grid-template-columns:1fr}#side{position:absolute;right:0;top:0;bottom:0;width:min(440px,96vw);z-index:30;box-shadow:-20px 0 50px #000c}}
</style>
</head>
<body>
<div id="app">
<section id="map"><div class="top"><div class="pill"><b>VANNIKAWACHH</b> · SIMNET / ARDUPILOT FLIGHT LAB</div><div class="pill"><span class="live">●</span> <b id="src">CHECKING</b></div></div><div id="mapCanvas"></div></section>
<aside id="side">
<div class="title">High-Fidelity Flight Layer</div>
<div class="sub">The Render app handles the VanniKawachh mission. The actual 3D aircraft, terrain, rotor dynamics and ArduPilot flight physics are delegated to SIMNET when its SITL TCP session is configured.</div>
<div class="card"><div class="lab">SIMNET ENGINE</div><div class="simnet"><span id="simDot" class="dot"></span><div><b id="simState">NOT CONFIGURED</b><div id="simInfo" class="small">Set SIMNET_HOST + SIMNET_PORT from SIMNET's Ground Control Station panel.</div></div></div></div>
<div class="card"><div class="lab">LIVE TELEMETRY</div><div id="state" class="big ok">IDLE</div><div class="row"><span>Mission</span><span id="mission" class="val">—</span></div><div class="row"><span>GPS</span><span id="gps" class="val">—</span></div><div class="row"><span>Speed</span><span id="speed" class="val">0.0 m/s</span></div><div class="row"><span>Altitude</span><span id="alt" class="val">0.0 m</span></div><div class="row"><span>Mode</span><span id="mode" class="val">—</span></div><div class="row"><span>Battery</span><span id="battery" class="val">—</span></div></div>
<div class="card"><div class="lab">MISSION SEQUENCE</div><div class="seq"><div id="s1" class="step">Distress trigger</div><div id="s2" class="step">Arm / rotor spool</div><div id="s3" class="step">Vertical takeoff</div><div id="s4" class="step">Cruise to distress GPS</div><div id="s5" class="step">Hover at target</div><div id="s6" class="step">Open payload</div><div id="s7" class="step">Drop health kit</div><div id="s8" class="step">RTL / land</div></div></div>
<div class="card"><div class="lab">MISSION TARGET</div><div class="row"><span>Home</span><span id="home" class="val">—</span></div><div class="row"><span>Target</span><span id="target" class="val">—</span></div><div class="row"><span>Distance</span><span id="distance" class="val">—</span></div><div class="row"><span>Kit</span><span id="kit" class="val">SECURED</span></div></div>
<div class="btns"><button id="simnet" class="btn primary">OPEN SIMNET</button><button id="mp" class="btn">MISSION PLANNER GUIDE</button><button id="live" class="btn">LIVE HUB</button><button id="test" class="btn warn">TEST DISTRESS</button><button id="fit" class="btn">FIT ROUTE</button><button id="reset" class="btn">RESET MAP</button></div>
<div id="status" class="status">Loading flight console…</div><div class="card"><div class="lab">EVENT LOG</div><div id="log" class="log"></div></div>
<div class="note">SIMNET currently exposes its SITL session to a Ground Control Station over a session-specific TCP IP/port. This console is prepared to use that same endpoint through the VanniKawachh MAVLink bridge; it does not invent a fake browser physics engine.</div>
</aside></div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
(function(){
var $=function(id){return document.getElementById(id)};var map=L.map('mapCanvas',{zoomControl:true,worldCopyJump:true}).setView([21.1466,79.0889],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);var homeMarker=null,targetMarker=null,droneMarker=null,route=null,last=null,lastState='IDLE',lastMission=null,timer=null;
function log(m){var e=$('log');e.innerHTML+='<div>'+new Date().toLocaleTimeString()+' · '+m+'</div>';e.scrollTop=e.scrollHeight}
function status(m,k){$('status').textContent=m;$('status').className='status '+(k||'')}
function setMarker(kind,lat,lon){var icon=kind==='drone'?L.circleMarker([lat,lon],{radius:8,color:'#35e2b3',fillColor:'#35e2b3',fillOpacity:.95}):kind==='target'?L.circleMarker([lat,lon],{radius:8,color:'#ff6875',fillColor:'#ff6875',fillOpacity:.95}):L.circleMarker([lat,lon],{radius:7,color:'#68b8ff',fillColor:'#68b8ff',fillOpacity:.95});if(kind==='home'){if(homeMarker)homeMarker.setLatLng([lat,lon]);else homeMarker=icon.addTo(map).bindTooltip('SAFE LANDING / HOME')}else if(kind==='target'){if(targetMarker)targetMarker.setLatLng([lat,lon]);else targetMarker=icon.addTo(map).bindTooltip('DISTRESS TARGET')}else{if(droneMarker)droneMarker.setLatLng([lat,lon]);else droneMarker=icon.addTo(map).bindTooltip('DRONE')}}
function distFmt(m){if(m==null)return '—';return m<1000?Math.round(m)+' m':(m/1000).toFixed(2)+' km'}
function sequence(s){var done={s1:['ARMING','TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s2:['TAKEOFF','ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s3:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s4:['ENROUTE','HOVERING','DELIVERING','RTL','LANDING'],s5:['HOVERING','DELIVERING','RTL','LANDING','COMPLETED'],s6:['DELIVERING','RTL','LANDING','COMPLETED'],s7:['RTL','LANDING','COMPLETED'],s8:['RTL','LANDING','COMPLETED']};Object.keys(done).forEach(function(id){$(id).className='step '+(done[id].indexOf(s)>=0?'done':'')});var a={ARMING:'s2',TAKEOFF:'s3',ENROUTE:'s4',HOVERING:'s5',DELIVERING:'s6',RTL:'s8',LANDING:'s8'}[s];if(a)$(a).className='step active'}
function apply(d){last=d;var s=d.state||'IDLE';$('state').textContent=s;$('state').className='big '+(['TAKEOFF','ENROUTE','RTL','LANDING'].indexOf(s)>=0?'warn':'ok');$('mission').textContent=d.mission_id||'—';$('gps').textContent=d.lat!=null?Number(d.lat).toFixed(5)+', '+Number(d.lon).toFixed(5):'—';$('speed').textContent=Number(d.speed_ms||0).toFixed(1)+' m/s';$('alt').textContent=Number(d.altitude_m||0).toFixed(1)+' m';$('mode').textContent=d.mode||s;$('battery').textContent=d.battery_pct==null?'—':Number(d.battery_pct).toFixed(0)+'%';$('kit').textContent=d.kit_dropped?'DROPPED':'SECURED';$('distance').textContent=distFmt(d.distance_m);$('home').textContent=d.home?Number(d.home[0]).toFixed(5)+', '+Number(d.home[1]).toFixed(5):'—';$('target').textContent=d.target?Number(d.target[0]).toFixed(5)+', '+Number(d.target[1]).toFixed(5):'—';$('simDot').className='dot '+(d.source==='simnet'&&d.connected?'on':'');$('simState').textContent=d.source==='simnet'?(d.connected?'SIMNET CONNECTED':'SIMNET DISCONNECTED'):'BROWSER FALLBACK';$('simInfo').textContent=d.source==='simnet'?'Live MAVLink telemetry from ArduPilot/SIMNET':'Real SIMNET not connected yet; configure SIMNET_HOST and SIMNET_PORT';$('src').textContent=d.source==='simnet'?'SIMNET / LIVE HUB':'LIVE HUB';sequence(s);if(s!==lastState){log('STATE → '+s);lastState=s}if(d.mission_id&&d.mission_id!==lastMission){log('MISSION '+d.mission_id);lastMission=d.mission_id}if(d.lat!=null)setMarker('drone',d.lat,d.lon);if(d.home)setMarker('home',d.home[0],d.home[1]);if(d.target){setMarker('target',d.target[0],d.target[1]);if(!route&&d.home)route=L.polyline([[d.home[0],d.home[1]],[d.target[0],d.target[1]]],{color:'#35e2b3',weight:4,opacity:.8}).addTo(map)}}
function fit(){var pts=[];if(last&&last.home)pts.push(last.home);if(last&&last.target)pts.push(last.target);if(last&&last.lat!=null)pts.push([last.lat,last.lon]);if(pts.length)map.fitBounds(pts,{padding:[40,40]})}
function poll(){fetch('/drone_state?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(function(d){status('Connected to /drone_state','good');apply(d)}).catch(function(e){status('Hub error: '+e.message,'err')}).finally(function(){timer=setTimeout(poll,700)})}
$('simnet').onclick=function(){window.open('https://www.simnet.aero/','_blank','noopener');log('Opened SIMNET workspace')};$('mp').onclick=function(){window.open('https://www.simnet.aero/post/introduction-to-mission-planner-sitl-simulation-with-simnet','_blank','noopener');log('Opened SIMNET Mission Planner guide')};$('live').onclick=function(){log('LIVE HUB → reconnect');poll()};$('test').onclick=function(){var b=$('test');b.disabled=true;status('Sending TEST DISTRESS…');fetch('/node-alert?node=WEB-FLIGHT&lat=21.128&lon=79.047&event=1&conf=0.99&pir=1&light=30').then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.text()}).then(function(t){log('DISTRESS → '+t);status('Distress accepted','good')}).catch(function(e){status('Trigger failed: '+e.message,'err')}).finally(function(){setTimeout(function(){b.disabled=false},700)})};$('fit').onclick=fit;$('reset').onclick=function(){map.setView(last&&last.home?last.home:[21.1466,79.0889],13)};status('Flight console ready','good');log('Flight console ready; SIMNET is the physics layer');poll()})();
</script>
</body></html>'''
